### ISSUE TITLE
write_dta does not work with variables with long strings 

### ISSUE THREAD

**Issue by Ales-G** [tidyverse/haven#566] opened 2021-01-19 15:35 UTC
I have noticed that write_dta is unable to save variables with very long strings. In particular I get the following`Error in write_dta_(data, normalizePath(path, mustWork = FALSE), version = stata_file_format(version),  : Writing failure: A provided string value was longer than the available storage size of the specified column`.

Here is an example of the issue:
```r
library(haven)

longFun <- function(n) {
  do.call(paste0, replicate(5000, sample(LETTERS, n, TRUE), FALSE))
}

longString <- data.frame(VeryveryveryveryveryveryveryveryveryveryVeryveryveryveryveryveryveryveryveryverylongname = longFun(1), stringsAsFactors = F)
write_dta(longString,"tst.dta")
```
Is there any way I can save variables of this kind? 
Thanks a lot for your help

Best

**Comment by sawoha** [comment] 2021-02-26 03:42
You cannot save that kind of variables by using write_dta() function because they exceed Stata's maximum size limits for variable names (32 characters) and values in these variables  (2,045 bytes for str# or 2,000,000,000 bytes for strL) (https://www.stata.com/products/comparison-of-limits/)

From my own experience, it looks like that write_dta() function in haven version 2.3.1 checks the length of values in each variable but does not check the length of variable names in a dataframe.

**Comment by hadley** [comment] 2021-04-08 18:59
Duplicate of #485, I think.

**Closed by hadley** 2021-04-08 18:59 UTC
