### ISSUE TITLE
write_dta fails with non-ascii in a tibble

### ISSUE THREAD

**Issue by karldw** [tidyverse/haven#309] opened 2017-08-18 22:17 UTC
Writing non-ascii characters in a `tbl_df` fails, while in a normal `data.frame` it's fine.  The error message is "Writing failure: A provided string value was longer than the available storage size of the specified column."
```r
library(haven)
library(tibble)
write_dta(data.frame(x = "é"), tempfile())  # works
write_dta(data_frame(x = "é"), tempfile())  # fails
```

**Comment by eborbath** [comment] 2017-12-14 23:32
same issue here, both with the `cran` and the `developmental version`. Not sure how to fix it.

Session Info:

`R version 3.4.3 (2017-11-30)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows >= 8 x64 (build 9200)

Matrix products: default

locale:
[1] LC_COLLATE=English_United States.1252 
[2] LC_CTYPE=English_United States.1252   
[3] LC_MONETARY=English_United States.1252
[4] LC_NUMERIC=C                          
[5] LC_TIME=English_United States.1252    

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] haven_1.1.0.9000 bindrcpp_0.2     rvest_0.3.2      xml2_1.1.1      
[5] stringr_1.2.0    dplyr_0.7.4      plyr_1.8.4       magrittr_1.5    

loaded via a namespace (and not attached):
 [1] Rcpp_0.12.14     knitr_1.17       bindr_0.1        devtools_1.13.4 
 [5] R6_2.2.2         rlang_0.1.4      httr_1.3.1       tools_3.4.3     
 [9] withr_2.1.0      selectr_0.3-1    git2r_0.19.0     yaml_2.1.15     
[13] assertthat_0.2.0 digest_0.6.12    tibble_1.3.4     curl_3.0        
[17] ghit_0.2.18      memoise_1.1.0    glue_1.2.0       stringi_1.1.6   
[21] compiler_3.4.3   forcats_0.2.0    pkgconfig_2.0.1 `

**Comment by karldw** [comment] 2017-12-15 00:01
Update: This doesn't happen on Linux. Probably Windows-only?

Anyway, the issue is the same with the development versions of tibble, pillar and haven.

```r
Session info ------------------------------------------------------------------
 setting  value                       
 version  R version 3.4.1 (2017-06-30)
 system   x86_64, mingw32             
 ui       Rgui                        
 language (EN)                        
 collate  English_United States.1252  
 tz       America/Los_Angeles         
 date     2017-12-14                  

Packages ----------------------------------------------------------------------
 package   * version    date       source                           
 base      * 3.4.1      2017-06-30 local                            
 compiler    3.4.1      2017-06-30 local                            
 datasets  * 3.4.1      2017-06-30 local                            
 devtools    1.13.4     2017-11-09 CRAN (R 3.4.2)                   
 digest      0.6.12     2017-01-27 CRAN (R 3.4.2)                   
 forcats     0.2.0      2017-01-23 CRAN (R 3.4.2)                   
 graphics  * 3.4.1      2017-06-30 local                            
 grDevices * 3.4.1      2017-06-30 local                            
 haven     * 1.1.0.9000 2017-12-14 Github (tidyverse/haven@7f2b479) 
 magrittr    1.5        2014-11-22 CRAN (R 3.4.2)                   
 memoise     1.1.0      2017-04-21 CRAN (R 3.4.2)                   
 methods   * 3.4.1      2017-06-30 local                            
 pillar      0.0.0.9000 2017-12-14 Github (r-lib/pillar@5a082e1)    
 Rcpp        0.12.14    2017-11-23 CRAN (R 3.4.2)                   
 rlang       0.1.4      2017-11-05 CRAN (R 3.4.2)                   
 stats     * 3.4.1      2017-06-30 local                            
 tibble    * 1.3.4.9003 2017-12-14 Github (tidyverse/tibble@60281b3)
 utils     * 3.4.1      2017-06-30 local                            
 withr       2.1.0      2017-11-01 CRAN (R 3.4.2)
```

**Comment by hadley** [comment] 2018-01-07 16:06
Deleting all the comments including session info - it's not useful here, and clutters up the discussion.

Note that a major difference between `data.frame` and `data_frame` is that `data.frame()` makes a factor.

**Comment by hadley** [comment] 2018-01-07 16:07
Duplicate of #258

**Closed by hadley** 2018-01-07 16:07 UTC
