### ISSUE TITLE
Haven converts some labelled Stata variable into numeric rather than haven_labelled

### ISSUE THREAD

**Issue by jkhanson1970** [tidyverse/haven#551] opened 2020-10-24 01:50 UTC
Please briefly describe your problem and what output you expect. If you have a question, please don't use this form. Instead, ask on <https://stackoverflow.com/> or <https://community.rstudio.com/>.

Please include a minimal reproducible example (AKA a reprex). If you've never heard of a [reprex](https://reprex.tidyverse.org/) before, start by reading <https://www.tidyverse.org/help/#reprex>.

---

Haven converts some labelled Stata variable into numeric rather than haven_labelled

```r
library(haven)
anes2016 <- read_dta("anes2016subset.dta")
```

In the provided dataset, the variables Sex, RaceEthnic, EducLevel, HSgrad, and BAplus should all become haven_labelled upon import into R. As far as I know, they are no different in Stata than many other variables in the dataset that do become haven_labelled upon import: each variable has value labels in Stata. In previous versions of the same dataset, prior to adding the Sex variable, Haven converted all the above-listed variables into haven_labelled.
[anes2016subset.dta.zip](https://github.com/tidyverse/haven/files/5432281/anes2016subset.dta.zip)

**Comment by NilsEnevoldsen** [comment] 2020-11-22 20:26
I was just stung with this and have identified the proximate cause. The issue is with empty value labels. I have a reproducible example.

In Stata:

```stata
input x y
0 0
end

lab def xlab 0 "Foo"
lab val x xlab

lab def ylab 0 "Bar"
lab val y ylab

lab def ylab 0 "", modify // This is one way to create an "empty" value label. It does *not* create a value label with an empty string for value 0.
label list
save ex1

label drop ylab
label list
save ex2
```

The first `label list` returns:

```
ylab:
xlab:
           0 Foo
```

And the second `label list` returns:

```
xlab:
           0 Foo
```

Importing these with haven yields:

```r
> read_dta("/Users/nils/ex1.dta")
# A tibble: 1 x 2
      x     y
  <dbl> <dbl>
1     0     0
> read_dta("/Users/nils/ex2.dta")
# A tibble: 1 x 2
          x     y
  <dbl+lbl> <dbl>
1   0 [Foo]     0
```

@jkhanson1970, in your case, the issue is with `V161331a`. To avoid this problem, you can run `label drop V161331a` — or, more generally, `labdu` from `labutil2` — to drop empty labels before saving with Stata.

**Comment by jkhanson1970** [comment] 2020-11-23 01:38
@NilsEnevoldsen Yes! That's the issue. Notably, it is dependent on the label list order. For any variable whose value labels appear on the label list prior to the one with empty value labels, haven reads the variable as numeric. For variables whose label values appear after the one with empty value labels, haven reads it as "haven-labelled."

	input x y z
	0 0 0
	end
	
	lab def xlab 0 "Foo"
	lab val x xlab
	
	lab def ylab 0 "Bar"
	lab val y ylab
	
	lab def ylab 0 "", modify 
	
	lab def zlab 0 "FooBar"
	lab val z zlab
	
	label list
	save ex3

Importing with haven yields:

    library(haven)
    read_dta("~/Desktop/ex3.dta")
    #> # A tibble: 1 x 3
    #>       x     y          z
    #>   <dbl> <dbl>  <dbl+lbl>
    #> 1     0     0 0 [FooBar]

<sup>Created on 2020-11-22 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

Thank you.

**Comment by NilsEnevoldsen** [comment] 2020-12-17 14:44
This is fixed in https://github.com/WizardMac/ReadStat/releases/tag/v1.1.5

**Comment by hadley** [comment] 2021-04-08 18:37
And that's now in haven 😄

**Closed by hadley** 2021-04-08 18:37 UTC
