### ISSUE TITLE
Confusing/misleading error message for write_sav  when SPSS-invalid column names present

### ISSUE THREAD

**Issue by dswpg** [tidyverse/haven#542] opened 2020-08-20 13:58 UTC
When a column name has spaces or other unacceptable-in-SPSS column names, the error codes are a  bit cryptic.

Perhaps the addition of the word 'column' or "column or row" (presuming that rownames are supported - I've haven't tried) before the word "name" in the error message would clear things up. 

We spent a long time thinking there was a problem in the filename we were writing to...

`haven::write_sav(tribble(~`a b`, 1,2),  'out.sav')`
Error in write_sav_(data, normalizePath(path, mustWork = FALSE), compress = compress) : 
  Writing failure: A provided name contains an illegal character.

NOTE: There are backticks around the a b, but it doesn't show correctly in the parser.

`haven::write_sav(tribble(~ALL, 1,2),  'out.sav')`
rror in write_sav_(data, normalizePath(path, mustWork = FALSE), compress = compress) : 
  Writing failure: A provided name is a reserved word.

Looking further, it looks like the error codes are probably from the underlying library, and not from haven.   One solution could be to add code to the validate_sav function that checks against (some?) of SPSS column naming rules. 

See: https://www.ibm.com/support/knowledgecenter/SSLVMB_23.0.0/spss/base/syn_variables_variable_names.html

Probably a bit of a moving target, as reserved words are probably not static.

**Comment by evanmiller** [comment] 2020-08-26 01:46
See #408

**Comment by hadley** [comment] 2021-04-08 21:02
Minimal reprex:

``` r
df <- data.frame(`a b ` = 1, check.names = FALSE)
haven::write_sav(df, tempfile())
#> Error: Writing failure: A provided name contains an illegal character.
```

<sup>Created on 2021-04-08 by the [reprex package](https://reprex.tidyverse.org) (v2.0.0)</sup>

Duplicate of #463.

**Closed by hadley** 2021-04-08 21:02 UTC
