### ISSUE TITLE
Writing failure: A provided name contains an illegal character. Error while saving R data into Stata format

### ISSUE THREAD

**Issue by resuf** [tidyverse/haven#531] opened 2020-06-22 16:53 UTC
I am using haven package to write the R dataset into Stata format. 

This is the error I am getting.

```r
write_dta(road_panel, "road_panel.dta", version = 14, label = attr(data,"label"))
Error in write_dta_(data, normalizePath(path, mustWork = FALSE), version = stata_file_format(version),  : 
 Writing failure: A provided name contains an illegal character.
```
I also tried a slightly different code but its the same.

```r
write_dta(road_panel, "road_panel_stata.dta")
   
Error in write_dta_(data, normalizePath(path, mustWork = FALSE), version = stata_file_format(version),  : Writing failure: A provided name contains an illegal character.
```

How can I successfully export the data into Stata format?

**Comment by dswpg** [comment] 2020-08-20 14:14
Perhaps you have a column name that doesn't meet STATA standards.
See: 
[https://www.stata.com/manuals13/u11.pdf](https://www.stata.com/manuals13/u11.pdf)

> 
> A name is a sequence of one to 32 letters (A–Z and a–z), digits (0–9), and underscores ( ).
> Programmers: Local macro names can have no more than 31 characters in the name; see
> [U] 18.3.1 Local macros.
> Stata reserves the following names:
> all float n skip
> b if N str#
> byte in pi strL
> coef int pred using
> cons long rc with
> double
> You may not use these reserved names for your variables.
> The first character of a name must be a letter or an underscore. We recommend, however, that
> you not begin your variable names with an underscore. All of Stata’s built-in variables begin with an
> underscore, and we reserve the right to incorporate new variables freely.
> Stata respects case; that is, myvar, Myvar, and MYVAR are three distinct names.
> All objects in Stata— not just variables— follow this naming convention

I had a similar problem with SPSS column names..

**Comment by jorgesinval** [comment] 2021-01-28 17:34
I can confirm the behavior... try `janitor::clean_names(df)``and repeat the process.

**Comment by hadley** [comment] 2021-04-08 21:00
Duplicate of #463

**Closed by hadley** 2021-04-08 21:00 UTC
