### ISSUE TITLE
Value labels missing in string variable with user defined missing values

### ISSUE THREAD

**Issue by stefanmr** [tidyverse/haven#247] opened 2016-12-01 09:51 UTC
First, i would like to thank you for the package, as well as all the other packages you made!!!

I am trying to import database from SPSS into R using "read_sav()". There is no error, but I notice that for most variables, the value labels are missing. Note that there are user-defined missing values, but for me it is irrelevant if they are converted to NA (they are all really missing).

So I wanted to prepare a minimal example, just one variable with value labels - BUT when I tested with only this variable, the conversion went OK and I got value labels in R. Testing more, I deleted all variables before the variable in question, and the value labels are there ONLY for the first STRING variable, then missing for all STRING the variables after.

It looks like "haven" is correctly labelling only numeric variables in my SPSS file, having a special problem with STRING variables (in the whole file, the numeric variables with value labels are imported correctly). When examining in R, the problematic variables are all "atomic" and value labels are missing.

I cannot attach the SPSS files... But here is the R output.
Variables:
- Pol: first STRING variable - CONVERSION OK
- Godine: second STRING variable - PROBLEM missing value labels
- Akcident2012: NUMERIC variable - CONVERSION OK
- NezgodaRadniStaz: STRING variable - PROBLEM
- ZanimanjeRecode: NUMERIC variable - CONVERSION OK

> Classes ‘tbl_df’, ‘tbl’ and 'data.frame':	5268 obs. of  5 variables:
 $ Pol             :Class 'labelled'  atomic [1:5268] A A A A ...
  .. ..- attr(*, "label")= chr "Pol"
  .. ..- attr(*, "format.spss")= chr "A22"
  .. ..- attr(*, "labels")= Named chr [1:2] "A" "B"
  .. .. ..- attr(*, "names")= chr [1:2] "Muški" "Ženski"
 $ Godine          : atomic  C C B B ...
  ..- attr(*, "label")= chr "Godine života"
  ..- attr(*, "format.spss")= chr "A22"
 $ Akcident2012    :Class 'labelled'  atomic [1:5268] 0 0 0 1 0 1 0 0 0 0 ...
  .. ..- attr(*, "label")= chr "Akcident tokom 2012"
  .. ..- attr(*, "format.spss")= chr "F8.0"
  .. ..- attr(*, "labels")= Named num [1:2] 0 1
  .. .. ..- attr(*, "names")= chr [1:2] "Ne" "Da"
 $ NezgodaRadniStaz: atomic  0 0 0 C ...
  ..- attr(*, "label")= chr "Nezgoda tokom celog radnog staža"
  ..- attr(*, "format.spss")= chr "A22"
 $ ZanimanjeRecode :Class 'labelled'  atomic [1:5268] 1 1 0 1 0 1 0 0 0 0 ...
  .. ..- attr(*, "label")= chr "Zanimanje"
  .. ..- attr(*, "format.spss")= chr "F8.0"
  .. ..- attr(*, "labels")= Named num [1:3] 0 1 2
  .. .. ..- attr(*, "names")= chr [1:3] "Lekar" "Sestra/Tehničar/Laboratorija" "Ostali"

The question is: Is there a way to import this file with all variables having value labels?

**Comment by hadley** [comment] 2017-01-25 14:30
Please provide a reproducible example. There are three things you need to include to make your example reproducible: required packages, data, and code.

1.  **Packages** should be loaded at the top of the script, so it's easy to
    see which ones the example needs. This is a good time to check that you're
    using the latest version of each package: it's possible you've discovered
    a bug that been fixed since you installed the package.

1.  The easiest way to include **data** in a question is to use `dput()` to 
    generate the R code to recreate it. For example, to recreate the `mtcars` 
    dataset in R, I'd perform the following steps:
  
    1. Run `dput(mtcars)` in R
    2. Copy the output
    3. In my reproducible script, type `mtcars <- ` then paste.
    
    Try and find the smallest subset of your data that still reveals
    the problem.

1.  Spend a little bit of time ensuring that your **code** is easy for others to
    read:

    * Make sure you've used spaces and your variable names are concise, yet
      informative.
    
    * Use comments to indicate where your problem lies.
    
    * Do your best to remove everything that is not related to the problem.  
      The shorter your code is, the easier it is to understand, and the 
      easier it is to fix.

Finish by checking that you have actually made a reproducible example by starting a fresh R session and copying and pasting your script in.

**Comment by hadley** [comment] 2017-01-30 14:25
I've closed this issue due to lack of requested reprex. If you still care about this bug, please open a new issue with a reprex.

**Closed by hadley** 2017-01-30 14:25 UTC
Labels: reprex
