### ISSUE TITLE
Allow SPSS strings longer than 255 characters [feature request]

### ISSUE THREAD

**Issue by BurninLeo** [tidyverse/haven#228] opened 2016-10-19 11:18 UTC
SPSS has been supporting strings with up to 32k characters for several versions by now. It would be helpful if `haven:write_sav()` could optionally support long strings. Currently, the function clips them to 255 characters.

**Comment by evanmiller** [comment] 2016-10-22 07:33
Not sure what's happening on the haven side, but ReadStat can write strings of length up to 32KB as of https://github.com/WizardMac/ReadStat/issues/72.

**Comment by hadley** [comment] 2016-10-27 14:11
@BurninLeo Please provide a reproducible example. There are three things you need to include to make your example reproducible: required packages, data, and code.

1.  **Packages** should be loaded at the top of the script, so it's easy to
    see which ones the example needs. This is a good time to check that you're
    using the latest version of each package: it's possible you've discovered
    a bug that been fixed since you installed the package.

1.  The easiest way to include **data** in a question is to use `dput()` to 
    generate the R code to recreate it. For example, to recreate the `mtcars` 
    dataset in R, I'd perform the following steps:
  
    1. Run `dput(mtcars)` in R
    2. Copy the output
    3. In my reproducible script, type `mtcars <- ` then paste.
    
    Try and find the smallest subset of your data that still reveals
    the problem.

1.  Spend a little bit of time ensuring that your **code** is easy for others to
    read:

    * Make sure you've used spaces and your variable names are concise, yet
      informative.
    
    * Use comments to indicate where your problem lies.
    
    * Do your best to remove everything that is not related to the problem.  
      The shorter your code is, the easier it is to understand, and the 
      easier it is to fix.

Finish by checking that you have actually made a reproducible example by starting a fresh R session and copying and pasting your script in.

**Comment by hadley** [comment] 2017-01-25 14:23
Closing due to absence of reprex

**Closed by hadley** 2017-01-25 14:23 UTC

**Comment by kerry-ja** [comment] 2017-01-27 22:06
I seem to have the same issue.  

The code I used:
require('haven') || devtools::install_github("tidyverse/haven")

c <- data.frame(1:2,c("Foo",paste(replicate(300, "A"), collapse = "")), stringsAsFactors = FALSE)
colnames(c) <- c("RowNum","Text")
write_sav(c, path=paste0("Desc Over 255 ",format(Sys.Date(), format="%B %d %Y"),".sav"))


When I tried to open the .sav file generated, the file is not opened, and in the SPSS output, I have:
GET 
  FILE='P:\Desc Over 255 January 27 2017.sav'. 
 
>Error.  Command name: GET FILE 
>Invalid SPSS Statistics data file: P:\Desc Over 255 January 27 2017.sav (DATA1204) 
>Execution of this command stops. 
 
>Error # 1405 in column 8.  Text: P:\Desc Over 255 January 27 2017.sav 
>Error when attempting to get a data file. 
DATASET NAME DataSet1 WINDOW=FRONT.

> sessionInfo()
R version 3.3.2 (2016-10-31)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 7 x64 (build 7601) Service Pack 1

locale:
[1] LC_COLLATE=English_United States.1252  LC_CTYPE=English_United States.1252    LC_MONETARY=English_United States.1252
[4] LC_NUMERIC=C                           LC_TIME=English_United States.1252    

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] openxlsx_4.0.0   RODBC_1.3-14     haven_1.0.0.9000

loaded via a namespace (and not attached):
 [1] Rcpp_0.12.9     digest_0.6.12   withr_1.0.2     assertthat_0.1  R6_2.2.0        git2r_0.18.0    magrittr_1.5    httr_1.2.1     
 [9] curl_2.3        devtools_1.12.0 forcats_0.2.0   tools_3.3.2     memoise_1.0.0   knitr_1.15.1    tibble_1.2     
> 

I have SPSS 20.0.0, but I also have an issue opening the file using PSPP (GNU pspp 0.10.4-g50f7b7)

**Comment by hadley** [comment] 2017-01-27 22:57
@kerry-ja Thanks for providing some code that illustrates the problem — it's a great start 😄 However 
GitHub issues use [markdown](https://guides.github.com/features/mastering-markdown/) and they're much easier to read if you learn a little bit about it. The most important thing is to put your R code inside a block that starts with ```` ```R ```` and ends with ```` ``` ````.  (And please don't include session info unless it's explicitly asked for, or you've used `reprex::reprex(..., si = TRUE)` to hide it away)

Finally, could you please open a new thread?

**Comment by hadley** [comment] 2017-01-27 22:58
Also this seems like the same issue as #266, so you might not need to do anything.
