### ISSUE TITLE
Is there a limitation for text length of the value labels for exporting the SPSS file?

### ISSUE THREAD

**Issue by wyutsai** [tidyverse/haven#431] opened 2019-02-15 01:58 UTC
I want to add value labels to my data and export the SPSS file. It's a simple example below:

``` r
library("haven")
sex <- c(1, 2, 1)
job <- c(2, 3, 1)
data <- data.frame(sex, job)
data$sex <- labelled(data$sex, c("男性" = 1, "女性" = 2))
data$job <- labelled(data$job, c("學生" = 1, "法律及工商服務業(包含顧問服務、土地代書、資訊服務維護、廣告業、及產品包裝設計、保全、影印、職業介紹)" = 2))
data$sex
#> <Labelled double>
#> [1] 1 2 1
#> 
#> Labels:
#>  value label
#>      1  男性
#>      2  女性
data$job
#> <Labelled double>
#> [1] 2 3 1
#> 
#> Labels:
#>  value
#>      1
#>      2
#>                                                                                                 label
#>                                                                                                  學生
#>  法律及工商服務業(包含顧問服務、土地代書、資訊服務維護、廣告業、及產品包裝設計、保全、影印、職業介紹)
```

<sup>Created on 2019-02-15 by the [reprex package](https://reprex.tidyverse.org) (v0.2.1)</sup>

Everything seems to be fine until here. But I get “R Session aborted” when I try to export the SPSS file by using ``` r write_sav(data,"C:\\Users\\Chucky Wang\\Desktop\\labels80.sav") ```

I think there is a limitation for text length of the value labels for exporting the SPSS file? 

Thanks!

**Comment by evanmiller** [comment] 2019-10-27 12:28
The value label size is limited to 120 bytes in the SPSS format.

However, "R Session aborted" indicates a bug in the code - I believe this issue is a duplicate of #395 which was fixed in https://github.com/tidyverse/haven/commit/e0d3d2e4235679bfa0ca39e2067cf47a222ee30e . Please try the development version of haven and see if that fixes your issue.

**Closed** 2019-11-06 20:49 UTC
