### ISSUE TITLE
read_dta & .name_repair

### ISSUE THREAD

**Issue by sigbertklinke** [tidyverse/haven#478] opened 2019-10-25 06:09 UTC
Hi,

I can not read in a data set from Stata. When I try I get the first error. If I follow the advice then I get "unused argument error".

How do I use .name_repair?

Best Sigbert

----

> library("haven")
> packageVersion("haven")

[1] ‘2.1.1’

> xp <- read_dta("XXX.dta")

Fehler in df_parse_dta_file(spec, encoding) :
  Evaluation error: Column name `Merge` must not be duplicated.
Use .name_repair to specify repair..

> mynr <- function(nms) { }
> xp <- read_dta("XXX.dta", .name_repair=mynr)

Fehler in read_dta("XXX.dta", .name_repair = mynr) :
  unbenutztes Argument (.name_repair = mynr)

**Comment by hadley** [comment] 2019-11-06 20:02
Can you please provide a minimal reprex (reproducible example)? The goal of a reprex is to make it as easy as possible for me to recreate your problem so that I can fix it: please [help me help you](https://nypdecider.files.wordpress.com/2014/08/help-me-help-you.gif)! 

If you've never heard of a reprex before, start by reading "[What is a reprex](http://reprex.tidyverse.org/articles/reprex.html)", and follow the advice further down the page. Please make sure your reprex is created with the reprex package as it gives nicely formatted output and avoids a number of common pitfalls.

**Comment by hadley** [comment] 2019-11-06 20:48
Duplicate of #436 which does have a reprex

**Closed by hadley** 2019-11-06 20:48 UTC
Labels: reprex
