### ISSUE TITLE
Issues when reading SAS datasets with associated format catalog

### ISSUE THREAD

**Issue by rogerjdeangelis** [tidyverse/haven#257] opened 2017-01-04 16:52 UTC
Issues when reading SAS datasets with associated format catalog

Win 7 64bit SAS 9.4 64bit

Your work with SAS datasets and SAS catalogs is appreciated.
Here are some areas for possible enhancements

1. I am unable to get value labels using the catalog_file option with read_sas.
2. The SAS/WPS code below demonstrates that the class.sas7bdat does have the $sex format attached.
3. The hex listing of the format catalog shows that the format catalog has the sex format and
   it is formatted correctly ( I removed the 'filler-growth areas )

* SAS TEST BEFORE R;
options validvarname=upcase;
libname fmt "d:/fmt";

options fmtsearch=(fmt.simple64bit);

proc format lib=fmt.simple64bit;
  value $sex
    'M'='Male'
    'F'='Female'
  ;
run;quit;

libname sd1 "d:/sd1";
data class(compress=no);
  format sex $sex.;
  set sashelp.class;
  put sex $1. +3 sex $sex.;
run;quit;

/* sex does have the format */
M   Male
F   Female
F   Female
F   Female
M   Male

* R CODE;
%utl_submit_r64('
library(haven);
sas <- read_sas("d:/sd1/class.sas7bdat",catalog_file= "d:/fmt/simple64bit.sas7bcat");
names(attr(sas[, "SEX"], "labels"));
head(sas);
str(sas);
');

> library(haven);
sas <- read_sas("d:/sd1/class.sas7bdat",catalog_file= "d:/fmt/simple64bit.sas7bcat");
names(attr(sas[, "SEX"], "labels"))
;head(sas);str(sas);

LOG

NULL
# A tibble: 6 × 5
     NAME   SEX   AGE HEIGHT WEIGHT
    <chr> <chr> <dbl>  <dbl>  <dbl>
1  Alfred     M    14   69.0  112.5
2   Alice     F    13   56.5   84.0
3 Barbara     F    13   65.3   98.0
4   Carol     F    14   62.8  102.5
5   Henry     M    14   63.5  102.5
6   James     M    12   57.3   83.0
Classes 'tbl_df', 'tbl' and 'data.frame':	19 obs. of  5 variables:
 $ NAME  : chr  "Alfred" "Alice" "Barbara" "Carol" ...
 $ SEX   : chr  "M" "F" "F" "F" ...
 $ AGE   : num  14 13 13 14 14 12 12 15 13 12 ...
 $ HEIGHT: num  69 56.5 65.3 62.8 63.5 57.3 59.8 62.5 62.5 59 ...
 $ WEIGHT: num  112 84 98 102 102 ...
 - attr(*, "label")= chr "CLASS"
>

[sas7bcat.txt](https://github.com/tidyverse/haven/files/685312/sas7bcat.txt)

**Comment by hadley** [comment] 2017-01-24 15:37
Can you please clearly state the problem, provide a minimal reproducible example using R code (a remote SAS file is fine), and use markdown formatting to make the issue easier to read.

**Comment by rogerjdeangelis** [comment] 2017-01-24 20:05
Please keep this problem open

See example with log above

All the code to create a SAS dataset with format, which you can do with the free WPS software, and the R code has been given

**Comment by hadley** [comment] 2017-01-25 14:36
@rogerjdeangelis please read http://github.com/jennybc/reprex#what-is-a-reprex and https://guides.github.com/features/mastering-markdown/, then update your issue so it's easier for me to read, and includes code that I can copy and paste into R to create the problem.

**Comment by hadley** [comment] 2017-01-30 14:25
I've closed this issue due to lack of requested reprex. If you still care about this bug, please open a new issue with a reprex.

**Closed by hadley** 2017-01-30 14:25 UTC
Labels: reprex
