### ISSUE TITLE
Missing values in Stata .dta files parsed as NaN

### ISSUE THREAD

**Issue by m-sostero** [tidyverse/haven#279] opened 2017-03-14 21:13 UTC
Missing observations in numeric variables in Stata (denoted by `.`) are parsed as `NaN` (not `NA`) by haven.

Steps to reproduce:

Create a dummy data set in Stata (13):
```stata
gen x=.
set obs 2
replace x = 2 in 2
save dummy.dta
```

Saved as .dta file format 117.
The variable is of type `float`;  the code for missing observation (`.`) should be `(+1.000000X+7f)` per [dta file format specs](http://www.stata.com/help.cgi?dta_117)

Import in R:

```R
> read_dta("dummy.dta")
# A tibble: 2 × 1
      x
  <dbl>
1   NaN
2     2
```

**Comment by m-sostero** [comment] 2017-03-14 21:18
Also, Stata has different semantics for missing values in string variables. They are effectively zero-length strings. Maybe haven should treat zero-length strings as `NA` when importing data?

**Comment by g3o2** [comment] 2017-04-08 21:52
String missing to NA would not be a major issue, however, numeric missing to NaN is a huge issue.

**Comment by hadley** [comment] 2017-07-07 17:30
Duplicate of #223, which has been fixed.

**Closed by hadley** 2017-07-07 17:30 UTC
