### ISSUE TITLE
read_sav reads character empty columns as numeric

### ISSUE THREAD

**Issue by samuelhuerga** [tidyverse/haven#311] opened 2017-08-25 12:31 UTC
In read_sav, if I try to read a character empty column (i.e, all values are empty string: ""), it is shown as a numeric column with values 6.01347e-154

```r
test <- data_frame(col = c("",""))
test
write_sav(test, "~/test.sav")

test_read <- read_sav("~/test.sav")
test_read
```

```r
> test
# A tibble: 2 x 1
    col
  <chr>
1      
2      

> test_read
# A tibble: 2 x 1
           col
         <dbl>
1 6.01347e-154
2 6.01347e-154
```
In SPSS it appears correctly:
![image](https://user-images.githubusercontent.com/12885915/29714133-04cd19a0-89a2-11e7-82b3-39358b5c2d4e.png)
![image](https://user-images.githubusercontent.com/12885915/29714141-0ebabd14-89a2-11e7-90cf-f07a4f0b80f5.png)

I've tried new version 1.1.0, but still occurs.
Is there something I am missing?

Thanks!

**Comment by ecortens** [comment] 2017-10-02 15:48
I'm seeing this same issue, in haven 1.1.0 from CRAN and haven 1.1.0.9000 on github (7f2b4796f76e44b88914e57c251318d9871055d1).

I tried installing haven 1.0.0 from CRAN, and the issue is still present.

However, it is not present in 0.2.1 from CRAN.

I'm seeing the issue in R 3.4.1 on both Windows 10 and MacOS 10.12.6.

**Comment by evanmiller** [comment] 2017-10-06 09:14
Should be fixed in https://github.com/WizardMac/ReadStat/commit/d0c922b136449347b0a5f86be450104efeb76381

**Comment by ecortens** [comment] 2017-10-06 19:19
Thanks @evanmiller! I've just submitted PR #316 to haven, which incorporates the latest fix in ReadStat.

**Closed** 2018-01-07 16:03 UTC
