### ISSUE TITLE
Interaction between SASxport and haven Yields Unusable Data

### ISSUE THREAD

**Issue by billdenney** [tidyverse/haven#358] opened 2018-03-03 21:24 UTC
When loading both SASxport and haven in the same session (a bad idea that I found in code I inherited), the labelled class fails to work on columns with classes "labelled" and "factor".

The error occurs here (https://github.com/tidyverse/haven/blob/746eb3e8c456136c8ff047478741b7d1625ec039/R/labelled.R#L40) where x is a factor and not a character or numeric.

**Comment by hadley** [comment] 2018-03-04 15:50
This is basically a duplicate of #329 (it has the same fix)

**Closed by hadley** 2018-03-04 15:50 UTC
