### ISSUE TITLE
"x and labels must be same type" still not resolved when user_na = TRUE

### ISSUE THREAD

**Issue by jmetzel** [tidyverse/haven#406] opened 2018-09-24 09:55 UTC
Hi,

I've just come across the issue that when I try to print an SPSS dataset I've read in via haven (v. 1.1.2) it fails with "Error: `x` and `labels` must be same type". 

This issue is fixed in #110, but - apparently - only when the 'user_na' argument is set to FALSE (as it is by default). 

I cross-checked and I only get the Error when i set 'user_na=TRUE'. When I read the file in with 'user_na=FALSE' the tibble is printed appropriately.

Maybe you could look into that. 

Sincerely,
Julian

**Comment by sydeaka** [comment] 2019-01-19 17:51
I was able to reproduce the error.

``` r
#install.packages('haven')


library('haven')
(sav <- system.file("files", "testdata.sav", package = "foreign"))
#> [1] "/opt/R/3.5.2/lib/R/library/foreign/files/testdata.sav"
x = read_spss(file=sav, user_na = FALSE)
print(head(x))  # works
#> # A tibble: 5 x 16
#>   numeric numeric_long_la… factor_numeric factor_n_long_v… factor_n_coded_…
#>     <dbl>            <dbl> <dbl+lbl>      <dbl+lbl>        <dbl+lbl>       
#> 1       1            NA     1              1                1              
#> 2       2            NA     2              2                2              
#> 3       3             3.33  3             NA               NA              
#> 4      NA             4    NA              2                5              
#> 5       3            NA    NA              1               NA              
#> # … with 11 more variables: factor_n_duplicated <dbl+lbl>,
#> #   factor_n_undeclared <dbl+lbl>, factor_n_undeclared2 <dbl+lbl>,
#> #   string <chr>, string_500 <chr>, string_miss <chr>,
#> #   factor_s_coded_miss <chr+lbl>, factor_s_duplicated <chr+lbl>,
#> #   factor_s_undeclared <chr+lbl>, factor_s_undeclared2 <chr+lbl>,
#> #   date <date>

x = read_spss(file=sav, user_na = TRUE)
print(head(x)) #fails
#> Error: `x` and `labels` must be same type
```

<sup>Created on 2019-01-19 by the [reprex package](https://reprex.tidyverse.org) (v0.2.1)</sup>

**Comment by hadley** [comment] 2019-01-19 18:06
Thank you @sydeaka!

**Comment by hadley** [comment] 2019-01-24 00:13
Slightly simpler reprex

``` r
library(haven)
sav <- system.file("files", "testdata.sav", package = "foreign")
x <- read_spss(file = sav, user_na = TRUE)

x$numeric_long_label
#> <Labelled SPSS double>
#> [1] 1.00000 2.00000 3.33333 4.00000      NA
#> Missing range:  [1, 2]
x$numeric_long_label[1:3]
#> Error: `x` and `labels` must be same type
```

<sup>Created on 2019-01-23 by the [reprex package](https://reprex.tidyverse.org) (v0.2.1.9000)</sup>

**Comment by hadley** [comment] 2019-01-24 00:14
And that reveals this issue is a duplicate of #219 😄

**Closed by hadley** 2019-01-24 00:14 UTC
Labels: bug, help wanted :heart:
