### ISSUE TITLE
Error occurred when reading SPSS file

### ISSUE THREAD

**Issue by h2appy** [tidyverse/haven#244] opened 2016-11-30 02:34 UTC
dataset <- read_sav(file = 'Q3-2032.sav')

Error in eval(substitute(expr), envir, enclos) : 
  Failed to parse /Users/me/Documents/workspace/R/data/Q3-2032.sav: Unable to convert string to the requested encoding (invalid byte sequence).

temporary solution:
1. Open 'Q3-2032.sav' in SPSS, and save it as a new.sav file.
2. Execute read_sav(file = 'new.sav'), no error occurred now.

My environment:
OSX 10.11.6
Rstudio 1.0.44
R 3.3.2
haven 1.0.0

**Comment by h2appy** [comment] 2016-11-30 03:41
<img width="944" alt="2016-11-30 11 34 42" src="https://cloud.githubusercontent.com/assets/11326053/20738930/b73c06d4-b6f1-11e6-9cb5-7b662647ae0c.png">

After comparing the files: Q3-2032.sav and new.sav, I found that Q3-2032.sav has GBK encoding.

**Comment by hadley** [comment] 2017-01-25 14:29
Please provide a reproducible example. There are three things you need to include to make your example reproducible: required packages, data, and code.

1.  **Packages** should be loaded at the top of the script, so it's easy to
    see which ones the example needs. This is a good time to check that you're
    using the latest version of each package: it's possible you've discovered
    a bug that been fixed since you installed the package.

1.  The easiest way to include **data** in a question is to use `dput()` to 
    generate the R code to recreate it. For example, to recreate the `mtcars` 
    dataset in R, I'd perform the following steps:
  
    1. Run `dput(mtcars)` in R
    2. Copy the output
    3. In my reproducible script, type `mtcars <- ` then paste.
    
    Try and find the smallest subset of your data that still reveals
    the problem.

1.  Spend a little bit of time ensuring that your **code** is easy for others to
    read:

    * Make sure you've used spaces and your variable names are concise, yet
      informative.
    
    * Use comments to indicate where your problem lies.
    
    * Do your best to remove everything that is not related to the problem.  
      The shorter your code is, the easier it is to understand, and the 
      easier it is to fix.

Finish by checking that you have actually made a reproducible example by starting a fresh R session and copying and pasting your script in.

**Comment by hadley** [comment] 2017-01-25 14:29
@evanmiller maybe there's already enough info here for you to see the problem?

**Comment by evanmiller** [comment] 2017-01-25 14:35
@h2appy Can you please provide a link to the file that's not importing?

@hadley This issue may be similar to https://github.com/WizardMac/ReadStat/issues/85 (however that issue was affecting SAS files so it's not a duplicate of this one)

**Comment by hadley** [comment] 2017-01-30 14:26
I've closed this issue due to lack of requested reprex. If you still care about this bug, please open a new issue with a reprex.

**Closed by hadley** 2017-01-30 14:26 UTC
Labels: reprex

**Comment by evanmiller** [comment] 2017-01-30 21:09
@hadley I would prefer to keep this issue open (or transfer it to ReadStat) as it is a legitimate bug likely affecting users working with Chinese language data sets.

**Comment by hadley** [comment] 2017-01-30 22:27
@evanmiller sure - I'm probably overly aggressive about closing issues without reprexes
