### ISSUE TITLE
Reading blocks, columns, compressed files

### ISSUE THREAD

**Issue by AHoerner** [tidyverse/haven#164] opened 2016-05-24 04:46 UTC
This is a feature request, not a bug.

I am working with some big data sets (Census, Current Population Survey, 5 to 50 GB range) that stretch the limit of my computer’s memory. I am also trying to write code to let other people with ordinary computers do the same things. It would be helpful if I could use the very helpful file translation features of this package package to extract pieces of the file without having to get the whole file into memory. My intended use would be to do some preprocessing and subsetting on chunks small enough that they will not run into memory limits. I see this request as providing better integration between Haven and dplyr, as an attractive feature of dplyr is the ability to do some data preparation and selection in the database rather than in RAM. This would extend t hat benefit to the very first steps of data preparation.

I am suggesting/requesting three feature. In order of priority:
1. By far the most important, skip a given number of lines or records and then read a block of lines or records of specified size (similar to the “n” argument in readLines). Basically I just want to read the file a chunk at a time;
2. Read the file but only hand R certain columns specified by number or variable name;
3. Read directly from gz or zipped files. This would be most helpful in conjunction with (1) or (2), or if Haven could read data directly into a .rdata file (I have observed that the rdata format is quite compressed., at least on the sort of rectangular arrays I am working with.  R can open files in .rdata format that run into memory limits if you use read.table to import a flat file containing the same data.

Thanks for your attention!   --Andrew Hoerner

**Comment by evanmiller** [comment] 2017-02-01 15:23
The second request (selective column import) is a duplicate of #248 -- please track progress over there.

**Comment by hadley** [comment] 2018-02-15 21:34
And the first request is #194 

I think the 3rd request is already possible.

**Closed by hadley** 2018-02-15 21:34 UTC
Labels: feature
