### ISSUE TITLE
spss.format and write_save()

### ISSUE THREAD

**Issue by DionAkkerman** [tidyverse/haven#450] opened 2019-05-29 10:38 UTC
I'm using Haven to create several SPSS datafiles which are then combined in SPSS using the "add files" command. This command requires the SPSS data formats of matching columns to be identical across files so I set the format.spss attributes in R:
```r
spss_formats <- c("A20", "A80", "F4.0", "F8.2")
df_list <- df_list %>%
  purrr::map(~ purrr::map2_dfc(., spss_formats, ~ `attr<-`(.x, "format.spss", .y)))
```
If I open any of the files, the formats displayed in SPSS's variable view are correct but SPSS still throws a type mismatch error for string variables when using Add files. The diagnostic output shows that the formats are simply the longest field in that column for the particular file. I suspect that haven::write_save() is not correctly saving the formats.

**Comment by hadley** [comment] 2019-11-06 20:38
Can you please provide a minimal reprex (reproducible example)? The goal of a reprex is to make it as easy as possible for me to recreate your problem so that I can fix it: please [help me help you](https://nypdecider.files.wordpress.com/2014/08/help-me-help-you.gif)! 

If you've never heard of a reprex before, start by reading "[What is a reprex](http://reprex.tidyverse.org/articles/reprex.html)", and follow the advice further down the page. Please make sure your reprex is created with the reprex package as it gives nicely formatted output and avoids a number of common pitfalls.

In this case, you might be able to demonstrate the problem using `read_spss()`

**Comment by hadley** [comment] 2020-04-20 20:23
I've closed this issue due to lack of requested reprex. If you still care about this bug, please open a new issue with a reprex.

**Closed by hadley** 2020-04-20 20:23 UTC
Labels: reprex
