### ISSUE TITLE
read_data can read variable names with chinese characters but write_data gives error

### ISSUE THREAD

**Issue by anoopxaviour** [tidyverse/haven#354] opened 2018-02-23 11:17 UTC
```
library(haven)
DF_DATA <- read_dta("x14_2_Chinese.dta")
write_dta(DF_DATA, "out_Chinese.dta")
```

Getting error "Error: The following variable names are not valid Stata variables: `x<U+8BF6>`" from write_dta function while writing the chinese dataset. But we were able to read the same file using read_data function. Please help us to figure out the issue. Thanks in advance.

do file to create the sample file.
```
//Chinese
clear;
unicode encoding set "GB18030";
input c d x诶 str20 string_Chinese;
1 1 1 "诶比西";
2 2 2 "迪伊艾弗吉艾";
end;
label variable c "Chinese characters 诶比西迪伊艾弗吉艾尺艾杰开艾勒艾马艾娜哦屁吉吾艾儿艾丝提伊吾维豆贝尔维艾克斯吾艾贼德";
label define d 1 "诶比西" 2 "迪伊艾弗吉艾";
label values d d;
numlabel , add;
compress;
codebook , compact;
tab string_Chinese;
notes: Saved by Stata 14.2;
save x14_2_Chinese.dta , replace;
```

**Comment by hadley** [comment] 2018-02-23 11:30
Can you please provide a minimal reprex (reproducible example)? The goal of a reprex is to make it as easy as possible for me to recreate your problem so that I can fix it: please [help me help you](https://nypdecider.files.wordpress.com/2014/08/help-me-help-you.gif)! 

If you've never heard of a reprex before, start by reading "[What is a reprex](http://reprex.tidyverse.org/articles/reprex.html)", and follow the advice further down the page. Please make sure your reprex is created with the reprex package as it gives nicely formatted output and avoids a number of common pitfalls.

**Comment by anoopxaviour** [comment] 2018-02-23 12:44
``` r
library(haven)

x <- data.frame(var = c(1,2))

x["x诶"] <- c(3,4)

write_dta(x, "chinese.dta")
#> Error: The following variable names are not valid Stata variables: `x["x诶"]`
```

please see the session info below.

R version 3.3.3 (2017-03-06)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows >= 8 x64 (build 9200)

locale:
[1] LC_COLLATE=English_United States.1252  LC_CTYPE=English_United States.1252   
[3] LC_MONETARY=English_United States.1252 LC_NUMERIC=C                          
[5] LC_TIME=English_United States.1252    

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] haven_1.1.1  reprex_0.1.2

**Comment by hadley** [comment] 2018-02-23 13:22
(Please don't include session info unless it's explicitly asked for, or you've used `reprex::reprex(..., si = TRUE)` to hide it away. I've deleted it from your issue to avoid cluttering up the discussion)

**Comment by hadley** [comment] 2018-02-23 13:25
haven throws this error, because I was told stata only supports a limited set of characters (https://github.com/WizardMac/ReadStat/issues/46). Can you please point me to stata documentation that better describes the allowed set of characters?

**Comment by anoopxaviour** [comment] 2018-02-26 05:06
Thanks for clarifying! Yes, stata only supports a limited set of characters. I was trying with a stata file shared by my client. We were able to read it but it throws the error when export back.  I 'll check with them, the file might not be valid stata file. Once again thank you very much for your support.

**Comment by hadley** [comment] 2018-06-20 11:09
Duplicate of #383

**Closed by hadley** 2018-06-20 11:09 UTC
