### ISSUE TITLE
Cannot write multiple .dta files in same session

### ISSUE THREAD

**Issue by MokeEire** [tidyverse/haven#471] opened 2019-09-20 03:12 UTC
I am trying to write multiple files to .dta.  The first file will write, and then any use of write_dta() afterward results in the following error:

    Error in write_dta_(data, normalizePath(path, mustWork = FALSE), version = 
    stata_file_format(version)) : 
        Writing failure: Unable to write data.

The only solution I came up with was restarting my computer each time which obviously was not ideal.  Restarting the R session, nor closing RStudio and re-opening solved the issue.

The code used when this error occurred can be found [here](https://github.com/MokeEire/Upwork/blob/master/YRBS/yrbss_file_conversion.R)

**Comment by hadley** [comment] 2019-11-06 20:06
Can you please provide a minimal reprex (reproducible example)? The goal of a reprex is to make it as easy as possible for me to recreate your problem so that I can fix it: please [help me help you](https://nypdecider.files.wordpress.com/2014/08/help-me-help-you.gif)! 

If you've never heard of a reprex before, start by reading "[What is a reprex](http://reprex.tidyverse.org/articles/reprex.html)", and follow the advice further down the page. Please make sure your reprex is created with the reprex package as it gives nicely formatted output and avoids a number of common pitfalls.

**Comment by hadley** [comment] 2020-04-20 20:45
I've closed this issue due to lack of requested reprex. If you still care about this bug, please open a new issue with a reprex.

**Closed by hadley** 2020-04-20 20:45 UTC
Labels: reprex
