### ISSUE TITLE
SPSS Error # 1405 when reading haven-created SAV files containing 256+ byte strings

### ISSUE THREAD

**Issue by rubenarslan** [tidyverse/haven#266] opened 2017-01-26 15:37 UTC
SPSS (v.20.0) cannot read files written by haven if there are any strings longer than 255 characters (or bytes, strings with umlauts need to be shorter still).

### to reproduce 

```R
n <- 256
df <- data.frame(long = paste(rep("a", n), collapse = ""), stringsAsFactors = FALSE)
write_sav(df, path = "test.sav")
```

### test files
I made three test files.
In all, I wrote a long string consisting of "a" with one "b" at the end.

1. is 255 characters, written in haven, it opens in SPSS.
2. is 256 characters, written in haven, it doesn't open in SPSS.
3. is the first one, with the string width increased from 255 to 256 in SPSS (added one a). This one opens fine too.

[test_files.zip](https://github.com/tidyverse/haven/files/732616/test_files.zip)

[original discusson](https://github.com/tidyverse/haven/issues/262)

PS.: @evanmiller Let me know if I should raise these issues directly in ReadStat. I only use ReadStat through haven though, so wouldn't be able to make reprexes.

**Comment by hadley** [comment] 2017-01-27 23:05
You're sure you have the latest haven? That doesn't crash for me.

**Comment by hadley** [comment] 2017-01-27 23:05
Ooops, sorry, this isn't about crashing but about SPSS not being able to read the files.

**Comment by evanmiller** [comment] 2017-07-08 18:37
Should be fixed in https://github.com/WizardMac/ReadStat/commit/f6aef4c9db5e50be7f8e22bb52776d7c6074baa2

**Comment by rubenarslan** [comment] 2017-07-10 14:57
Great. Can I test with my real example already or do I need to wait until this is pulled into haven?

**Comment by evanmiller** [comment] 2017-07-10 15:41
I think this fix just barely missed the 1.1.0 cutoff, so you'll have to wait until it gets pulled into haven.

**Comment by aganalyticsemc** [comment] 2017-12-14 17:08
@evanmiller When do you expect to have this fix pulled into haven? I am experiencing the same issue as @rubenarslan . SPSS won't open a .sav saved using write.sav if one of the dataframes contains a string with more than 255 bytes. I've tried to manually adjust ReadStat as you mentioned in the fix. However, this didn't seem to work :/

**Comment by hadley** [comment] 2018-01-07 16:13
Please try with latest version on github.

**Comment by sjkiss** [comment] 2018-02-15 15:46
Am I right that this fix has been integrated to the development version of Haven? 

I have an SPSS file I am using with collaborators. When I've imported via haven, made changes and then try to re-export via write_sav() it produces a corrupted file exactly as described above. There are at least two variables with value lengths longer than 255 characters, identified in the script below.  

This self-contained code will replicate the problem. Compare file `out.sav` which is my original, downloaded from [here](https://dataverse.scholarsportal.info/file.xhtml?fileId=62627&version=RELEASED&version=.1) with the file `write_out.sav` which, in my workflow, is corrupted. I'm not sure if this is the most efficient way to replicate the problem for you. I hope it's satisfactory.
```
#Setworking directory to where you wish
#setwd()
#Load dataverse
library(dataverse)
#Warning: This changes two environment variables that are necessary to search dataverse with the dataverse package; I haven't been able to write this script where these are only changed locally. It's not a huge deal, but be aware.
Sys.setenv("DATAVERSE_SERVER" = "dataverse.scholarsportal.info")
Sys.setenv("DATAVERSE_KEY" = "e66bfc71-7665-40bf-83c2-b7e5a6dc2c33")
#Get the problematic file as a binary file (I think)
out<-get_file('second_survey.tab', 'hdl:10864/10985', 'original')
#Write it out in SPSS format
writeBin(out, 'out.sav')
#AFAIK I have the development version of haven installed
library(haven)
#Read the sav file in
read_out<-read_sav(out)

#Now Write it out and test
write_sav(read_out, 'write_out.sav')
#Two variables that cause problems are 
library(dplyr)
read_out %>% 
  select(contains('storetime'))
```

**Comment by hadley** [comment] 2018-02-15 17:06
Could you please rework your reproducible example to use the [reprex package](http://reprex.tidyverse.org) and create a new issue? That makes it easier to see both the input and the output, formatted in such a way that I can easily re-run in a local session.

**Comment by rubenarslan** [comment] 2018-02-16 09:38
I think it's still the same problem, that you can also see with my more minimal reprex. This is after installing the latest haven from master.

``` r
library(haven)
n <- 256
df <- data.frame(long = paste(rep("a", n), collapse = ""), stringsAsFactors = FALSE)
write_sav(df, path = "test.sav")
```

>Error.  Command name: GET FILE 
>Invalid SPSS Statistics data file: /Users/rubenarslan/Dropbox/MPI/codebook/test.sav (DATA1204) 
>Execution of this command stops. 
>Error # 1405 in column 8.  Text: /Users/rubenarslan/Dropbox/MPI/codebook/test.sav 
>Error when attempting to get a data file. 
GET 
  FILE='/Users/rubenarslan/Dropbox/MPI/codebook/test.sav'.

**Comment by hadley** [comment] 2018-02-16 14:13
This appears to still be a problem even with latest readstat

**Comment by evanmiller** [comment] 2018-02-16 14:19
Error message from #346:

```
Error. Command name: GET FILE
Invalid SPSS Statistics data file: test.sav (DATA1204)
Execution of this command stops.
Error # 1405 in column 8. Text: test.sav
Error when attempting to get a data file.
GET
FILE='test.sav'.
```

My current theory is as follows. Variables in an SAV file contain a "virtual" variable for each 256-byte chunk. ReadStat gives each virtual variable the same name. However, in the sample file provided,  it appears that SPSS assigns a unique name to each virtual variable (e.g. `LONG` and `LONG0`). I'll see if the PSPP docs have anything to say about this.

**Comment by evanmiller** [comment] 2018-02-16 14:31
PSPP has this to say:

> The ‘name’ fields should be unique within a system file. System files written by SPSS that contain very long string variables with similar names sometimes contain duplicate names that are later eliminated by resolving the very long string names (see Very Long String Record). PSPP handles duplicates by assigning them new, unique names.

[Source](https://www.gnu.org/software/pspp/pspp-dev/html_node/Variable-Record.html#Variable-Record)

**Comment by rubenarslan** [comment] 2018-02-16 14:43
Does it help you verify your theory if I generate files with more 5*256 letters or so?

**Comment by hadley** [comment] 2018-02-16 14:57
@rubenarslan I just updated haven with @evanmiller's latest code. Can you please try again now?

**Comment by rubenarslan** [comment] 2018-02-16 15:09
Unfortunately, the same error occurs after an update with devtools. I also attached a 512 character-string file in case that helps.

[tests.zip](https://github.com/tidyverse/haven/files/1731754/tests.zip)

>GET 
  FILE='/Users/rubenarslan/Dropbox/MPI/codebook/test_x.sav'. 
 
>Error.  Command name: GET FILE 
>Invalid SPSS Statistics data file: test_x.sav (DATA1204) 
>Execution of this command stops. 
>Error # 1405 in column 8.  Text: test_x.sav 
>Error when attempting to get a data file.

**Comment by evanmiller** [comment] 2018-02-16 15:38
Thanks. Might be an issue with the [Variable Display Parameter](https://www.gnu.org/software/pspp/pspp-dev/html_node/Variable-Display-Parameter-Record.html#Variable-Display-Parameter-Record)... I'll have another update to test soon.

**Comment by evanmiller** [comment] 2018-02-16 16:07
@hadley Try the latest ReadStat.

For future reference someone should give this issue a more descriptive name e.g. 

> SPSS Error # 1405 when reading haven-created SAV files containing 256+ byte strings

**Comment by rubenarslan** [comment] 2018-02-16 16:10
@evanmiller that might well be it. In SPSS you also cannot lengthen a string without first increasing the variable display parameter. I'll try with the next update.

**Comment by hadley** [comment] 2018-02-16 16:11
@rubenarslan try now

**Comment by rubenarslan** [comment] 2018-02-16 16:23
Well, it now writes the 256 character file and SPSS can open it. Yay!
But if I go to 512 I get two _visible_ V0000001 and V0000002. It's not concatenated in the long variable. In the addition, the "long" variable has the type comma at 512 chars, Date at 1024 chars etc. Seems pretty weird...

**Comment by rubenarslan** [comment] 2018-02-16 16:26
I just noticed that `foreign` also cannot read the haven-generated files, but it has more informative error messages. Maybe this is helpful for writing tests in R? Unless the foreign implementation is really bad, but at least it's quite robust, right?

## 256 chars
> foreign::read.spss("test_x.sav")
Error in foreign::read.spss("test_x.sav") : 
  error reading system-file header
In addition: Warning message:
In foreign::read.spss("test_x.sav") :
  test_x.sav: Bad format specifier byte (0)

## 512 chars
> foreign::read.spss("test_y.sav")
Error in foreign::read.spss("test_y.sav") : 
  error reading system-file header
In addition: Warning message:
In foreign::read.spss("test_y.sav") :
  test_y.sav: String variable VAR0 has numeric format specifier COMMA


## 1024 chars
> foreign::read.spss("test_z.sav")
Error in foreign::read.spss("test_z.sav") : 
  error reading system-file header
In addition: Warning message:
In foreign::read.spss("test_z.sav") :
  test_z.sav: String variable VAR0 has numeric format specifier F

**Comment by evanmiller** [comment] 2018-02-16 17:06
@rubenarslan Please open new and separate issues against ReadStat for these.

Note that ReadStat has a command-line interface, so we should be able to debug these without getting haven involved.

```
readstat /path/to/spss-input.sav /path/to/readstat-output.sav
```

**Comment by wibrt** [comment] 2018-05-22 07:03
More feedback,
when i open an spss .sav made by spss; then there are no errors
then after loading this dataset, making some calculations; saving the dataset as .sav in R;
the same dataset is unable to be opened in spss

i don't know if this has anything to do with the labels, since the data column to which SPSS refers in its error message was not changed

referring: SPSS Error # 1405

**Comment by hadley** [comment] 2019-01-23 23:53
Closing since this thread is long and seems to combine multiple issues. Please file new issues (with reprexes) if you're still seeing problems.

**Closed by hadley** 2019-01-23 23:53 UTC
Labels: bug, readstat

**Comment by rubenarslan** [comment] 2019-01-24 06:55
The original issue has been fixed in ReadStat. https://github.com/WizardMac/ReadStat/issues/122
