### ISSUE TITLE
Only R can read a SAS dataset created by R?

### ISSUE THREAD

**Issue by rogerjdeangelis** [tidyverse/haven#249] opened 2016-12-05 23:01 UTC
Only R can read a SAS dataset created by R?

Is the objective to create a SAS data set that can be read outside of R?

I know this is not an easy problem and it works well within R.
Your efforts are appreciated.
Others have been able to import a SAS dataset outside of R,
but I cannot.

I can't get an answer from those who suceeded.,

Notes on write_sas

  1. write_sas does work in a round trip with R.
  2. SAS, WPS, Stattransfer and Carolina cannot read
     the SAS datasets cretaed by R?

THIS WORKS Win7 R3.2.4 or UBUNTU 64bit)

%utl_submit_r64('
library(haven);
file1 <- "d:/sd1/mtcars.sas7bdat";
haven::write_sas(mtcars, file1);
DF_1 <- haven::read_sas(file1);
head(DF_1,3);
');

/*
> library(haven);file1 <- "d:/sd1/mtcars.sas7bdat";haven::write_sas(mtcars, file1);
DF_1 <- haven::read_sas(file1);head(DF_1,3);
# A tibble: 3 × 11
    mpg   cyl  disp    hp  drat    wt  qsec    vs    am  gear  carb
  <dbl> <dbl> <dbl> <dbl> <dbl> <dbl> <dbl> <dbl> <dbl> <dbl> <dbl>
1  21.0     6   160   110  3.90 2.620 16.46     0     1     4     4
2  21.0     6   160   110  3.90 2.875 17.02     0     1     4     4
3  22.8     4   108    93  3.85 2.320 18.61     1     1     4     1
*/

THIS DOES NOT (SAS9.4M2 64bit - Win7 64bit)

proc contents data="d:/sd1/mtcars.sas7bdat";
;run;quit;

276   proc contents data="d:/sd1/mtcars.sas7bdat";
ERROR: File d:/sd1/mtcars.sas7bdat is not a SAS data set.
277   ;run;

* free wps version does create a valid SAS dataset;
%utl_submit_wps64('
libname sd1 "d:/sd1";
options set=R_HOME "C:/Program Files/R/R-3.3.1";
libname wrk "%sysfunc(pathname(work))";
proc r;
submit;
library(haven);
data(mtcars);
endsubmit;
import r=mtcars data=wrk.mtcars;
run;quit;
');

proc contents data=mtcars;
run;quit;

Alphabetic List of Variables and Attributes

 #    Variable    Type    Len

 9    AM          Num       8
11    CARB        Num       8
 2    CYL         Num       8
 3    DISP        Num       8
 5    DRAT        Num       8
10    GEAR        Num       8
 4    HP          Num       8
 1    MPG         Num       8
 7    QSEC        Num       8
 8    VS          Num       8
 6    WT          Num       8

**Comment by hadley** [comment] 2017-01-25 14:33
Duplicate of #224

**Closed by hadley** 2017-01-25 14:33 UTC
