### ISSUE TITLE
Examples fail with ellipsis 0.2.0

### ISSUE THREAD

**Issue by QuLogic** [tidyverse/haven#457] opened 2019-06-22 00:37 UTC
An [automated rebuild](https://apps.fedoraproject.org/koschei/build/6587024) with ellipsis 0.2.0 is now [failing](https://kojipkgs.fedoraproject.org/work/tasks/7216/35707216/build.log):

```r
> ### ** Examples
> 
> s1 <- labelled(c("M", "M", "F"), c(Male = "M", Female = "F"))
> s2 <- labelled(c(1, 1, 2), c(Male = 1, Female = 2))
> s3 <- labelled(c(1, 1, 2), c(Male = 1, Female = 2),
+                label="Assigned sex at birth")
> 
> # Unfortunately it's not possible to make as.factor work for labelled objects
> # so instead use as_factor. This works for all types of labelled vectors.
> as_factor(s1)
[1] Male   Male   Female
Levels: Female Male
> as_factor(s1, labels = "values")
Error: 1 components of `...` were not used.
We detected these problematic arguments:
* `labels`
Did you misspecify an argument?
Backtrace:
    x
 1. \-forcats::as_factor(s1, labels = "values")
 2.   \-(function (env = parent.frame()) ...
 3.     \-ellipsis:::stop_dots(...)
Execution halted
```

I'm not sure if this is a bug in `forcats` or `ellipsis` instead, but since the initial call is in this package, I've reported it here.

**Comment by hadley** [comment] 2019-06-24 14:39
Duplicate of #458

**Closed by hadley** 2019-06-24 14:39 UTC
