### ISSUE TITLE
labelled_spss() & write_sav(): user NA's only retained for double vectors

### ISSUE THREAD

**Issue by atungate** [tidyverse/haven#532] opened 2020-06-24 13:58 UTC
User specified missing values are dropped when writing unless the vector is type double--(hopefully) demonstrated below. Please let me know if you need to see my output, or if you want a screenshot of the SPSS variable view (that shows no NA values for integer / character vectors). 

Below, all columns have SPSS user-specified missing values. I included the missing values in some of the vectors. 

Thanks!! -Andrew

```r
library(haven)
library(tibble)

df_write <- tibble(int_no_NA_SPSSnavals = labelled_spss(as.integer(c(1:10)), na_values = c(-997, -998)),
                   int_no_NA_SPSSnarange = labelled_spss(as.integer(c(1:10)), na_range = c(-997, -998)),
                   int_yes_NA_SPSSnavals = labelled_spss(as.integer(c(1:8, -997, -998)), na_values = c(-997, -998)),
                   int_yes_NA_SPSSnarange = labelled_spss(as.integer(c(1:8, -997, -998)), na_range = c(-997, -998)),
                   int_SPSSlabel_navals = labelled_spss(as.integer(c(1:8, -997, -998)), label = "Integer Vector", na_values = c(-997, -998)),
                   dbl_no_NA_SPSSnavals = labelled_spss(as.double(c(1:10)), na_values = c(-997, -998)),
                   dbl_no_NA_SPSSnarange = labelled_spss(as.double(c(1:10)), na_range = c(-997, -998)),
                   dbl_yes_NA_SPSSnavals = labelled_spss(as.double(c(1:8, -997, -998)), na_values = c(-997, -998)),
                   dbl_yes_NA_SPSSnarange = labelled_spss(as.double(c(1:8, -997, -998)), na_range = c(-997, -998)),
                   dbl_SPSSlabel_navals = labelled_spss(as.double(c(1:8, -997, -998)), label = "Double Vector", na_values = c(-997, -998)),
                   chr_no_NA_SPSSnavals = labelled_spss(as.character(c(1:10)), na_values = c("-997", "-998")),
                   chr_yes_NA_SPSSnavals = labelled_spss(as.character(c(1:8, -997, -998)), na_values = c("-997", "-998")),
                   chr_SPSSlabel_navals = labelled_spss(as.character(c(1:8, -997, -998)), label = "Character Vector", na_values = c("-997", "-998")))

# Check missing values
sapply(df_write, function(j) attributes(j)$na_, simplify = FALSE) # looks good

# Check labels
sapply(df_write, function(j) attributes(j)$label, simplify = FALSE) # looks good

# Head-up--writes to current WD
write_sav(df_write, "df_na_test.sav")

# Read back in
df_read <- read_sav("df_na_test.sav", user_na = TRUE)

# Check missing values
sapply(df_read, function(j) attributes(j)$na_, simplify = FALSE) # write_sav only retained NA vals and range for double vectors (same in SPSS)

# Check labels
sapply(df_read, function(j) attributes(j)$label, simplify = FALSE) # Labels look good


> sessionInfo()
R version 4.0.0 (2020-04-24)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 10 x64 (build 18363)

Matrix products: default

locale:
[1] LC_COLLATE=English_United States.1252  LC_CTYPE=English_United States.1252    LC_MONETARY=English_United States.1252
[4] LC_NUMERIC=C                           LC_TIME=English_United States.1252    

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] tibble_3.0.1 haven_2.3.1 

loaded via a namespace (and not attached):
 [1] Rcpp_1.0.4.6     fansi_0.4.1      assertthat_0.2.1 crayon_1.3.4     R6_2.4.1         lifecycle_0.2.0  magrittr_1.5     pillar_1.4.4    
 [9] cli_2.0.2        rlang_0.4.6      rstudioapi_0.11  vctrs_0.3.0      ellipsis_0.3.1   forcats_0.5.0    tools_4.0.0      readr_1.3.1     
[17] glue_1.4.1       hms_0.5.3        compiler_4.0.0   pkgconfig_2.0.3 

```

**Comment by beckerbenj** [comment] 2020-07-01 00:09
Same issue here. I think the problem is somewhat new and this originally worked in older package versions (but interestingly installing an older haven version does not solve the issue for me?).

**Comment by sachseka** [comment] 2020-07-01 06:13
I have the same problem...

**Comment by antaldaniel** [comment] 2020-07-11 11:24
The problem appears to be that `write_sav()` does not writes l`abelled_spss classes`, and strips the user-defined missing value range at writing.

`### Read and change to missing labelled -----
iris_read <- haven::read_spss(
  system.file("examples", "iris.sav", package = "haven"))
iris$Species[1] <- 8; iris$Species[2] <- 9
na_values <- 8:9
names (na_values) <- c("unidentified", "missing")
labelled::na_values(iris$Species) <- na_values 
inherits(iris$Species, "haven_labelled_spss")
attr(iris$Species, "na_values")`

The variable is changed to class `haven_labelled_spss`  and the missing values are correctly attributed.

### Save it ------------------------------------
temp_dir <- tempdir()
haven::write_sav(iris, 
                 path = file.path(temp_dir, "re-iris.sav")
)

### Re-read it ---------------------------------
re_iris <- haven::read_sav(
  file.path("temp_dir, "re-iris.sav"))

inherits(re_iris$Species, "haven_labelled_spss")
attr(re_iris$Species, "na_values")`
  
Species was saved as `haven_labelled_spss` but re-read as `haven_labelled`.

**Comment by hadley** [comment] 2021-04-08 21:00
Duplicate of #409

**Closed by hadley** 2021-04-08 21:00 UTC
