### ISSUE TITLE
write_sav doesn't preserve na_values for character or integer vectors

### ISSUE THREAD

**Issue by jaydennord** [tidyverse/haven#571] opened 2021-03-30 21:13 UTC
As the title says, `write_sav` doesn't preserve missing data value codes for character or integer vectors. Example:

```r
library(tidyverse)
library(haven)

d <- tibble(
  a = 1:5,
  b = letters[1:5],
  c = as.numeric(a)
) %>%
  mutate(
    a = labelled_spss(a, na_values = c(-98L, -99L)),
    b = labelled_spss(b, na_values = c("-98", "-99")),
    c = labelled_spss(c, na_values = c(-98, -99))
  )

write_sav(d, "test.sav")
```

But, when opened by SPSS, only variable "c" has missing value codes.

**Comment by hadley** [comment] 2021-04-08 18:51
Duplicate of #532

**Closed by hadley** 2021-04-08 18:51 UTC
