### ISSUE TITLE
Missing data read as NaN instead of NA

### ISSUE THREAD

**Issue by skanskan** [tidyverse/haven#251] opened 2016-12-15 10:44 UTC
Hello.

I'm using haven 1.0.0  on Windows 10.
When I use 
`read_sav("myfile.sav")`
to read an SPSS sav file, missing data are read as NaN instead of the conventional NA.
Is it a bug? Is it supposed to be like that?
Can I change it with a simple flag when reading the file?

I know I could modify all my NaN afterwards 
`myfile[myfile=="NaN"] <- "NA"`
but I'd prefer to get it done directly from haven.  

Regards

**Comment by hadley** [comment] 2017-01-25 14:34
Duplicate of #223

**Closed by hadley** 2017-01-25 14:34 UTC
