### ISSUE TITLE
Subsetting loses variable labels

### ISSUE THREAD

**Issue by Crismoc** [tidyverse/haven#392] opened 2018-07-27 15:47 UTC
When I import SPSS  data with read_sav() variable labels are correctly imported. 

```{r}
data<-haven::read_sav("data.sav")
str(data$sexo)
> 'labelled' num [1:738] 1 0 0 1 1 0 1 0 0 0 ...
 - attr(*, "label")= chr "Sexo (0: Hombre, 1: Mujer)"
 - attr(*, "format.spss")= chr "F8.2"
 - attr(*, "display_width")= int 10
 - attr(*, "labels")= Named num [1:2] 0 1
  ..- attr(*, "names")= chr [1:2] "Mujer" "Hombre"
```
Then I create multiple subsamples of it and write new SPSS data frames with write_sav(). 

```{r}
haven::write_sav(data[sample(nrow(datos),350),], "data_subsample.sav")
```
When opening the new dataframes in SPSS -or reading them back with read_sav()- variable labels are lost. Is there a way of fixing this?

<img width="959" alt="screenshot 2018-07-27 11 38 55" src="https://user-images.githubusercontent.com/8093092/43330926-8c12b692-9192-11e8-8c9f-b5c894785531.png">

Thanks!

```{r}
R version 3.5.0 (2018-04-23)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows >= 8 x64 (build 9200)

Matrix products: default

locale:
[1] LC_COLLATE=English_United States.1252  LC_CTYPE=English_United States.1252   
[3] LC_MONETARY=English_United States.1252 LC_NUMERIC=C                          
[5] LC_TIME=English_United States.1252    

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] haven_1.1.1

loaded via a namespace (and not attached):
[1] compiler_3.5.0 magrittr_1.5   tools_3.5.0    pillar_1.2.3   tibble_1.4.2  
[6] yaml_2.1.19    Rcpp_0.12.17   forcats_0.3.0  rlang_0.2.1  
```

**Comment by Crismoc** [comment] 2018-07-30 04:44
Thanks, @ekothe. I get the problem now, although I still cannot produce a random sample of size `n` without losing variable labels. I tried using dplyr's `sample_n`, but the result is the same.

```{r}
accidents  <- haven::read_sav("accidents.sav")
str(accidents$agecat)
> 'labelled' num [1:6] 1 2 3 1 2 3
>  - attr(*, "label")= chr "Age category"
>  - attr(*, "format.spss")= chr "F4.0"
>  - attr(*, "labels")= Named num [1:3] 1 2 3
>   ..- attr(*, "names")= chr [1:3] "Under 21" "21-25" "26-30"

accidents.s <- dplyr::sample_n(accidents, 2)
str(accidents.s$agecat)
> 'labelled' num [1:2] 3 2
>  - attr(*, "labels")= Named num [1:3] 1 2 3
>   ..- attr(*, "names")= chr [1:3] "Under 21" "21-25" "26-30"
```

Maybe this departs from a haven issue, but it would be useful if someone con shed some light on how to make a random sample without losing variable labels.

**Comment by ekothe** [comment] 2018-07-30 08:43
@Crismoc if you're only subsetting according to row you could write the labels to a list using `my_labels <- labels(accidents)` and then assign the labels back to the dataframe after subsetting using `var_label(accidents) <- my_labels`

**Comment by Crismoc** [comment] 2018-07-30 14:16
Thanks for the help, @ekothe. It is a suitable solution, although it would be useful having a command for random sampling the rows that behaves similar to dplyr's filter.

**Comment by hadley** [comment] 2018-08-28 18:31
Would someone mind creating a minimal reprex by generating a vector with `labelled()`, putting it in a data frame, and then showing that attributes are lost after subsetting?

**Comment by huftis** [comment] 2018-08-29 09:41
This behaviour reported in this bug report looks very similar to the one in the (now fixed) bug #360.

**Comment by Crismoc** [comment] 2018-08-29 13:48
I downloaded tidyverse from Github and now the error is the same:

```{r}
> devtools::install_github("hadley/tidyverse")
> titanic <- haven::read_sav("https://www.sheffield.ac.uk/polopoly_fs/1.547009!/file/Titanic_2.sav")
> haven::write_sav(dplyr::sample_n(titanic, 100),  "titanic_100.sav")

Error in write_sav_(data, normalizePath(path, mustWork = FALSE), compress = compress) : 
  Not compatible with requested type: [type=NULL; target=double].
```
Still works fine if I do not use `sample_n` or `sample(nrow(titanic))`

**Comment by huftis** [comment] 2018-08-29 16:35
I can’t reproduce, @Crismoc. When running your code with the latest haven version from github, everything seems to work fine.

What does your ‘dplyr::sample_n(titanic, 100)’ object look like?

**Comment by Crismoc** [comment] 2018-08-29 16:49
My bad, I hadn't restarted the session. Although, the original problem persists. When running `write_sav()` with `sample_n()` you end up losing the variable labels:

```{r}
> titanic <- haven::read_sav("https://www.sheffield.ac.uk/polopoly_fs/1.547009!/file/Titanic_2.sav")
> haven::write_sav(dplyr::sample_n(titanic, 100),  "titanic_100.sav")
```
<img width="778" alt="screenshot 2018-08-29 13 46 10" src="https://user-images.githubusercontent.com/8093092/44802415-0d35ba80-ab92-11e8-96fc-335eb449d93e.png">

Instead, when not using ``sample_n()`, variables labels remain:

```{r}
haven::write_sav(titanic,  "titanic.sav")
```

<img width="784" alt="screenshot 2018-08-29 13 44 48" src="https://user-images.githubusercontent.com/8093092/44802420-12930500-ab92-11e8-838d-47428d4ca91a.png">

**Comment by huftis** [comment] 2018-08-29 18:45
BTW, @ekothe, while I agree that it’s much better to use `filter()` than `subset()`, the fact that `filter()` ‘works’ in this case (for variables like `fare`) is actually a *bug* in filter. It’s tracked in https://github.com/tidyverse/dplyr/issues/2432 (which might be difficult to understand, but see the many linked bug reports for a better explanation).

**Comment by hadley** [comment] 2019-01-24 15:06
I think the proposal to always use `haven_labelled` would create more problems than it solves, because more people would be force to confront an exotic variable type that doesn't actually bear on their analysis.

Instead I think you're better off creating a custom restore labels functions, something like this (untested, but should be close):

```R
restore_labels <- function(df, orig) {
  for (var in names(original)) {
    if (is.null(df[[var]]))
      next
    
    if (!is.null(attr(df[[var]], "label")))
      next
    
    if (is.null(attr(orig[[var]], "label")))
      next
    
    attr(df[[var]], "label") <- attr(orig[[var]], "label")
  }
  
  df
}
```

**Closed by hadley** 2019-01-24 15:06 UTC
Labels: feature

**Comment by larmarange** [comment] 2019-01-24 16:38
`labelled` package propose a `copy_labels` function doing exactly this: http://larmarange.github.io/labelled/reference/copy_labels.html
