### ISSUE TITLE
vctrs methods for haven_labelled

### ISSUE THREAD

**Issue by romainfrancois** [tidyverse/haven#510] opened 2020-04-29 08:06 UTC
``` r
library(vctrs)
library(haven)

x <- haven::labelled(c(1, 2, 3), c("xyz" = 1))
attr(x, "label") <- "A var label"

y <- haven::labelled(c(1), c("xyz" = 1))
attr(y, "label") <- "A different var label"

vec_c(x, y)
#> Error: Can't combine `..1` <haven_labelled> and `..2` <haven_labelled>.
#> x Some attributes are incompatible.
#> ℹ The author of the class should implement vctrs methods.
#> ℹ See <https://vctrs.r-lib.org/reference/faq-error-incompatible-attributes.html>.
vec_ptype2(x, y)
#> Error: Can't combine <haven_labelled> and <haven_labelled>.
#> x Some attributes are incompatible.
#> ℹ The author of the class should implement vctrs methods.
#> ℹ See <https://vctrs.r-lib.org/reference/faq-error-incompatible-attributes.html>.
```

<sup>Created on 2020-04-29 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

<details>

<summary>Session info</summary>

``` r
devtools::session_info()
#> ─ Session info ───────────────────────────────────────────────────────────────
#>  setting  value                       
#>  version  R version 4.0.0 (2020-04-24)
#>  os       macOS Mojave 10.14.6        
#>  system   x86_64, darwin17.0          
#>  ui       X11                         
#>  language (EN)                        
#>  collate  en_US.UTF-8                 
#>  ctype    en_US.UTF-8                 
#>  tz       Europe/Paris                
#>  date     2020-04-29                  
#> 
#> ─ Packages ───────────────────────────────────────────────────────────────────
#>  package     * version     date       lib source                          
#>  assertthat    0.2.1       2019-03-21 [1] CRAN (R 4.0.0)                  
#>  backports     1.1.6       2020-04-05 [1] CRAN (R 4.0.0)                  
#>  callr         3.4.3       2020-03-28 [1] CRAN (R 4.0.0)                  
#>  cli           2.0.2       2020-02-28 [1] CRAN (R 4.0.0)                  
#>  crayon        1.3.4.9000  2020-04-27 [1] Github (r-lib/crayon@dcf6d44)   
#>  desc          1.2.0       2018-05-01 [1] CRAN (R 4.0.0)                  
#>  devtools      2.3.0       2020-04-10 [1] CRAN (R 4.0.0)                  
#>  digest        0.6.25      2020-02-23 [1] CRAN (R 4.0.0)                  
#>  ellipsis      0.3.0       2019-09-20 [1] CRAN (R 4.0.0)                  
#>  evaluate      0.14        2019-05-28 [1] CRAN (R 4.0.0)                  
#>  fansi         0.4.1       2020-01-08 [1] CRAN (R 4.0.0)                  
#>  forcats       0.5.0       2020-03-01 [1] CRAN (R 4.0.0)                  
#>  fs            1.4.1       2020-04-04 [1] CRAN (R 4.0.0)                  
#>  glue          1.4.0       2020-04-03 [1] CRAN (R 4.0.0)                  
#>  haven       * 2.2.0.9000  2020-04-29 [1] Github (tidyverse/haven@5c32563)
#>  highr         0.8         2019-03-20 [1] CRAN (R 4.0.0)                  
#>  hms           0.5.3       2020-01-08 [1] CRAN (R 4.0.0)                  
#>  htmltools     0.4.0       2019-10-04 [1] CRAN (R 4.0.0)                  
#>  knitr         1.28        2020-02-06 [1] CRAN (R 4.0.0)                  
#>  lifecycle     0.2.0       2020-03-06 [1] CRAN (R 4.0.0)                  
#>  magrittr      1.5         2014-11-22 [1] CRAN (R 4.0.0)                  
#>  memoise       1.1.0       2017-04-21 [1] CRAN (R 4.0.0)                  
#>  pillar        1.4.3       2019-12-20 [1] CRAN (R 4.0.0)                  
#>  pkgbuild      1.0.7       2020-04-25 [1] CRAN (R 4.0.0)                  
#>  pkgconfig     2.0.3       2019-09-22 [1] CRAN (R 4.0.0)                  
#>  pkgload       1.0.2       2018-10-29 [1] CRAN (R 4.0.0)                  
#>  prettyunits   1.1.1       2020-01-24 [1] CRAN (R 4.0.0)                  
#>  processx      3.4.2       2020-02-09 [1] CRAN (R 4.0.0)                  
#>  ps            1.3.2       2020-02-13 [1] CRAN (R 4.0.0)                  
#>  R6            2.4.1       2019-11-12 [1] CRAN (R 4.0.0)                  
#>  Rcpp          1.0.4.6     2020-04-09 [1] CRAN (R 4.0.0)                  
#>  remotes       2.1.1       2020-02-15 [1] CRAN (R 4.0.0)                  
#>  rlang         0.4.5.9000  2020-04-27 [1] Github (r-lib/rlang@a90b04b)    
#>  rmarkdown     2.1         2020-01-20 [1] CRAN (R 4.0.0)                  
#>  rprojroot     1.3-2       2018-01-03 [1] CRAN (R 4.0.0)                  
#>  sessioninfo   1.1.1       2018-11-05 [1] CRAN (R 4.0.0)                  
#>  stringi       1.4.6       2020-02-17 [1] CRAN (R 4.0.0)                  
#>  stringr       1.4.0       2019-02-10 [1] CRAN (R 4.0.0)                  
#>  testthat      2.3.2       2020-03-02 [1] CRAN (R 4.0.0)                  
#>  tibble        3.0.1       2020-04-20 [1] CRAN (R 4.0.0)                  
#>  usethis       1.6.0       2020-04-09 [1] CRAN (R 4.0.0)                  
#>  vctrs       * 0.2.99.9011 2020-04-29 [1] Github (r-lib/vctrs@8a39ced)    
#>  withr         2.2.0       2020-04-20 [1] CRAN (R 4.0.0)                  
#>  xfun          0.13        2020-04-13 [1] CRAN (R 4.0.0)                  
#>  yaml          2.2.1       2020-02-01 [1] CRAN (R 4.0.0)                  
#> 
#> [1] /Users/romainfrancois/.R/library/4.0
#> [2] /Library/Frameworks/R.framework/Versions/4.0/Resources/library
```

</details>

**Comment by romainfrancois** [comment] 2020-04-29 08:07
This causes tests to fail for package `ipumsr` against dplyr 1.0.0: 

```r
test_that(
  "mismatched attributes in bind rows", {
    test1 <- tibble::tibble(
      x = haven::labelled(c(1, 2, 3), c("xyz" = 1)),
      y = 2:4
    )
    attr(test1$x, "label") <- "A var label"

    test2 <- tibble::tibble(
      x = haven::labelled(c(1), c("xyz" = 1)),
      z = "a"
    )
    attr(test2$x, "label") <- "A different var label"

    expect_warning(bound <- ipums_bind_rows(test1, test2))

    expect_equal(names(bound), c("x", "y", "z"))
    expect_equal(as.vector(bound$x), c(1, 2, 3, 1))
  })
```

```r
Error: Test failed: 'mismatched attributes in bind rows'
* Can't combine `..1$x` <haven_labelled> and `..2$x` <haven_labelled>.
x Some attributes are incompatible.
ℹ The author of the class should implement vctrs methods.
ℹ See <https://vctrs.r-lib.org/reference/faq-error-incompatible-attributes.html>.
Backtrace:
  1. testthat::expect_warning(bound <- ipums_bind_rows(test1, test2))
  9. vctrs::vec_default_ptype2(...)
 10. vctrs::stop_incompatible_type(...)
 11. vctrs:::stop_incompatible_type_combine(...)
 12. vctrs:::stop_incompatible_type_impl(...)
 13. vctrs:::stop_incompatible(...)
 14. vctrs:::stop_vctrs(...)
```

**Comment by romainfrancois** [comment] 2020-04-29 08:09
unless it's a vctrs problem ? cc @lionel-

**Comment by lionel-** [comment] 2020-04-29 09:03
If they have different attributes and they don't have a `c()` method, we can't combine them without vctrs methods.

**Comment by hadley** [comment] 2020-04-29 12:38
Duplicate of #496

**Comment by hadley** [comment] 2020-04-29 12:38
I'll work on it today or tomorrow

**Closed by hadley** 2020-04-29 12:38 UTC
