### ISSUE TITLE
SAS and WPS could not read the SAS dataset created by R

### ISSUE THREAD

**Issue by rogerjdeangelis** [tidyverse/haven#232] opened 2016-10-24 23:08 UTC
CONCLUSION ( On created SAS dataset from R)
1. SAS and WPS could not read the SAS dataset created by R even
   after fixing the dataset name issue
2. Missing datset name in SAS datset created from R.
   Slugging in the dataset name did not make the R SAS dataset readable by SAS
3. Min size for SAS is 128k with a lot of junk filler.
   Filler is unique to every SAS install?
4. SAS datasets are at least 128k. R and WPS are smaller
- create SAS dataset
  %utlfkil(d:/sd1/test.sas7bdat);
  libname sd1 "d:/sd1";
  data sd1.test(compress=no);
  xTHOMASx="FINDTHIS";
  ySUZANEy=.1;
  put ySUZANEy hex16.;
  run;quit;

3FB999999999999A
- analyze dataset;
  data _null_;
  infile "d:/sd1/test.sas7bdat" lrecl=80 recfm=f;
  input;
  if not (822 < _n_ < 1612);
  if _infile_ ne repeat('00'x,79) then list;
  *if index(_infile_,'FINDTHIS')>0 then stop;
  *if index(_infile_,'YSUZANEY')>0 then stop;
  run;quit;
# SAS DATASET

RULE:     ----+----1----+----2----+----3----+----4----+----5----+----6----+----7----+----8----+----9----+----0

1   CHAR  ............Âê.`³..Ï½’...Ç1Œ...."".33..2................"".33..2.3.#3.>.........
    ZONE  000000000000CE86B11CB9000C381111220330030000000000001111220330030302303001000000
    NUMR  0000000000002A10341FD280971C8F01220331224000000000318F0122033122431330E000310000

2   CHAR  ....SAS FILETEST                                                            DATA
    ZONE  00005452444454552222222222222222222222222222222222222222222222222222222222224454
    NUMR  0000313069C545340000000000000000000000000000000000000000000000000000000000004141

3   CHAR      ....é&.e.·ÚAé&.e.·ÚA..... ÌÀ..... ÌÀ....................9.0401M2X64_7PRO....
    ZONE  22220000E2169BD4E2169BD4000002CC000002CC0000000000000000000032333343533535540000
    NUMR  00000000969507A1969507A1000000C0000000C0001000101000000000009E0401D2864F702F0000

4   CHAR  ....................................................é&.e¥hv.¥hv.¥hv.............
    ZONE  0000000000000000000000000000000000000000000000000000E216A670A670A670000000000000
    NUMR  00000000000000000000000000000000000000000000000000009695586058605860000000000000

5   CHAR  ....w‘Ã4....é&.e.·ÚA............................................................
    ZONE  000079C30000E2169BD4000000000000000000000000000000000000000000000000000000000000
    NUMR  000071340000969507A1000000000000000000000000000000000000000000000000000000000000

NULLS

820 CHAR  ................v‘Ã4......../ù.......... þ..à........þ..........äü..0.......¤ü..
    ZONE  000000000000000079C3000000002F00000000002F00E00000001F0000000000EF0030000000AF00
    NUMR  0000000000000000613400000000F90002B0A0000E00010000004E00C00000004C00010000004C00

821 CHAR  @.......€ü..$.......Tü..,......._ü.._.......öû..4.......Âû..4.......Âû..........
    ZONE  400000008F00200000005F00200000002F0020000000FF0030000000CF0030000000CF0000000000
    NUMR  000001000C00400001004C00C0000100AC00A00001006B00400000002B00400000002B0000001000

```
       š™™™™™¹? = .1 3FB999999999999A
```

822 CHAR  š™™™™™¹?FINDTHISH...WOULD YOU SAY THAT IN GENERAL YOUR HEALTH IS?...HEALTH..AGE.
    ZONE  999999B3444454454000545442545254525445244244445442545524444542453000444454004440
    NUMR  A999999F69E4489380007F5C409F503190481409E075E521C09F520851C48093F000851C48001750

FILLER

1612CHAR  ¿.ð¿.ð¿.ð¿.ð¿.ð¿.ð¿.ð¿.ð¿.ð¿.,@..@..@.ð¿.ð?.ð¿..@..@..@..@..@..@..@..@.ð?.ð¿.ð¿.
    ZONE  B0FB0FB0FB0FB0FB0FB0FB0FB0FB0240040040FB0F30FB0040040040040040040040040F30FB0FB0
    NUMR  F00F00F00F00F00F00F00F00F00F0C000000000F00F00F00008008008008008008008000F00F00F0

1613CHAR  ð¿.ð¿.ð¿.ð¿.ð?..@..@.ð¿.ð¿..@.ð?.ð¿.ð¿..@.ð¿.ð¿..@.ð?..@.ð?-1
    ZONE  FB0FB0FB0FB0F30040040FB0FB0040F30FB0FB0040FB0FB0040F30040F3232222222222222222222
    NUMR  0F00F00F00F00F08000000F00F00000F00F00F00000F00F08000F00000FD10000000000000000000
1614                         -1                                      -1
1615               -1                            -1                            -1
1616                                   -1                                      -1
1617                                   -1                                      RI-1

1618CHAR                                 441.1000  ...........€êÒ@......ð¿......ð¿......ð¿
    ZONE  22222222222222222222222222222223332333322000000000008ED4000000FB000000FB000000FB
    NUMR  0000000000000000000000000000000441E100000000000000000A200000000F0000000F0000000F

1619CHAR  ......ð¿......ð¿......ð¿......ð¿......ð¿........................................
    ZONE  000000FB000000FB000000FB000000FB000000FB0000001000000000000000000000000000000000
    NUMR  0000000F0000000F0000000F0000000F0000000F0000004000000000000000000000000000000000

1625CHAR  ..................................................................þûÿÿ..........
    ZONE  000000000000000000000000000000000000000000000000000000000000000000FFFF0000000000
    NUMR  000000000000000000000000000000000000000000000000000000000000000000EBFF0000000000

1626CHAR  ......................................þûÿÿ......................................
    ZONE  00000000000000000000000000000000000000FFFF00000000000000000000000000000000000000
    NUMR  00000000000000000000000000000000000000EBFF00000000000000000000000000000000000000

1627CHAR  ..........þÿÿÿ..Ü......................ý............üÿÿÿ .......................
    ZONE  0000000000FFFF10D7000010000000000000001F000000000000FFFF200000000000000000000000
    NUMR  0000000000EFFFE0CF000060002020102000000D201000000000CFFF000000008000800004200000

1628CHAR  ................ÿÿÿÿ..........$.......,.............ýÿÿÿ4...........
    ZONE  0000000000000000FFFF10000000002000000020000000000000FFFF300000000000222222222222
    NUMR  8000041000000000FFFF800000000040800000C0800000000000DFFF400000000000000000000000

1629CHAR      DATASTEPXTHOMASXYSUZANEY.........üÿÿ4.......................................
    ZONE  2222445455455544445555554445000000000FFF3000000000000000000000000000000000000000
    NUMR  000041413450848FD138935A1E59000000000CFF4000400070000000000000000000000000000000

1630CHAR  ....................üÿÿÿ................ýÿÿÿ................ÿÿÿÿ................
    ZONE  00000000000000000000FFFF0000000000000000FFFF0000000000000000FFFF0000000000000000
    NUMR  000000000000C7000000CFFF1000600010006000DFFF1000400010004000FFFF1000500010005000

1631CHAR  þÿÿÿ................ûÿÿÿ................úÿÿÿ................ùÿÿÿ................
    ZONE  FFFF0000000000000000FFFF0000000000000000FFFF0000000000000000FFFF0000000000000000
    NUMR  EFFF1000700010007000BFFF0000000000000000AFFF00000000000000009FFF0000000000000000

1633CHAR  ....................öööö........÷÷÷÷‹............0".............................
    ZONE  00000000000000000000FFFF00000000FFFF80000000000013201000000000000000000000001000
    NUMR  000000000000000000006666200000007777B200C000000010240000100000000000200000006000

1634CHAR  ............“...ÿÿÿÿÿÿÿÿ........................................................
    ZONE  1000000000009000FFFFFFFF00000000000000000000000000000000000000000000000000000000
    NUMR  0000001000003F00FFFFFFFF00000000000000000000000000000000000000000000000000000000

1636CHAR  ............v‘Ã4................................................................
    ZONE  00000000000079C30000000000000000000000000000000000000000000000000000000000000000
    NUMR  0000000000006134000000000000000000000000000000000000000010002000100090001000B000

1637CHAR  ................................................................................
    ZONE  00000000000000000000000000000000000000000000000000000000000000000000001000000000
    NUMR  1000B000100080000000000000000000000000000000000000000000008040000000004080000000

1638CHAR  ................................................................................
    ZONE  00000000100000000000000000000000000000000000000000000000000000000000009000000000
    NUMR  00C08000C0800000000000000000000000000000000000004010108000000000000000DF00000000

1639CHAR  ................................ 32
    ZONE  00000000000000000000000000000000
    NUMR  10000000000000000001000000000000

%utl_submit_r64('
library(haven);
test<-read_sas("d:/sd1/test.sas7bdat");
class(test);
write_sas(test, "d:/sd1/testr.sas7bdat");
');

data _null_;
 infile "d:/sd1/testr.sas7bdat" lrecl=80 recfm=f;
 input;
 if _infile_ ne repeat('00'x,79) then list;
run;quit;
# R SAS DATASET

RULE:     ----+----1----+----2----+----3----+----4----+----5----+----6----+----7----+----8----+----9----+----0

1   CHAR  ............Âê.`³..Ï½’...Ç1Œ....3.."...1........................................
    ZONE  000000000000CE86B11CB9000C381111300200030000000000000000000000000000001000000000
    NUMR  0000000000002A10341FD280971C8F01300201010000000000000000000000000000004000000000

2   CHAR  ....SAS FILE................................................................DATA
    ZONE  00005452444400000000000000000000000000000000000000000000000000000000000000004454
    NUMR  0000313069C500000000000000000000000000000000000000000000000000000000000000004141

3   CHAR   ~ ~..@ß .ÖA..@ß .ÖA........................................9.0101M0W32_VSPRO...
    ZONE  2727004DA0D4004DA0D4000000000000000000000100000000000000000032333343533555554000
    NUMR  0E0E000F0361000F036100000000000000000400000020000000000000009E0101D0732F6302F000

14  CHAR  ........................€.......€...............h.......................<.......
    ZONE  00000000000000000000000080000000800000000000000060000000100000000000000030000000
    NUMR  0000000000000000007070000F00000000000000000000008F0000008000000000000000CF000000

15  CHAR  ,.......................<...............À.......@...............€.......@.......
    ZONE  2000000000000000000000003000000000000000C000000040000000000000008000000040000000
    NUMR  C0000000010000000F000000C0000000010000000E00000000000000000000000E00000000000000

16  CHAR  ........L.......4...............................................................
    ZONE  00000000400000003000000000000000000000000000000000000000000000000000000000000000
    NUMR  00000000CE0000004000000001000000000000000000000000000000000000000000000000000000

59  CHAR  ............................................ýÿÿÿÿÿÿÿ ...........        ........
    ZONE  00000000000000000000000000000000000000000000FFFFFFFF2000000000002222222200000000
    NUMR  00000000000000000000000000000000000000000000DFFFFFFF0000000000000000000000000000

60  CHAR  XTHOMASXYSUZANEYþûÿÿÿÿÿÿ........................................................
    ZONE  5544445555554445FFFFFFFF00000000000000000000000000000000000000000000000000000000
    NUMR  848FD138935A1E59EBFFFFFF00000000000000000000000000000000000000000000000000000000

61  CHAR  þûÿÿÿÿÿÿ........................................................üÿÿÿÿÿÿÿ(.......
    ZONE  FFFFFFFF00000000000000000000000000000000000000000000000000000000FFFFFFFF20000000
    NUMR  EBFFFFFF00000000000000000000000000000000000000000000000000000000CFFFFFFF80000000

62  CHAR  ............................................ÿÿÿÿÿÿÿÿ..................$.........
    ZONE  00000000000000000000000000000000000000000000FFFFFFFF1000000000100000002000000000
    NUMR  00000000800040208000000080004010000000000000FFFFFFFF8000000000C08000004080000000

63  CHAR  ........öööö....................÷÷÷÷............................................
    ZONE  00000000FFFF00000000000000000000FFFF00000000000000000000000000000000000010000000
    NUMR  00000000666600002000000000000000777700000000000000000000000000000000000000000000

64  CHAR  ................................................................................
    ZONE  00000000000000000000000000000000000000000000000000000000010000000000000000000000
    NUMR  10000000000000000000000000000000000000000000000000000000000000000000000000000000

```
                                                      š™™™™™¹? = .1 3FB999999999999A
```

65  CHAR  ........................................FINDTHISš™™™™™¹?........................
    ZONE  000000000000000000000000000000000000000044445445999999B3000000000000000000000000
    NUMR  000000000000000000000000000000000110000069E44893A999999F000000000000000000000000

116 CHAR  ................ 16
    ZONE  0000000000000000
    NUMR  0000000000000000

SLUGGING IN THE DATASET NAME TESTR

/\* lets add a file name to the R output */
data _null_;
 infile "d:/sd1/testr.sas7bdat" lrecl=80 recfm=f sharebuffers;
 file "d:/sd1/testr.sas7bdat" lrecl=80 recfm=f;
 input;
 if _n_=2 then do;
      substr(_infile_,13.5)='TESTR';
      list;
      stop;
 end;
 *if _infile_ ne repeat('00'x,79) then list;
run;quit;

RULE:     ----+----1----+----2----+----3----+----4----+----5----+----6----+----7----+----8-

2   CHAR  ....SAS FILETESTR
    ZONE  00005452444454555222222222222222222222222222222222222222222222222222222222222222
    NUMR  0000313069C545342000000000000000000000000000000000000000000000000000000000000000

proc contents data=sd1.testr;
run;quit;

1787  proc contents data=sd1.testr;
ERROR: File SD1.TESTR.DATA is not a SAS data set.

---

---

---

---

---

---

---
# ! WPS ;

%utl_submit_wps64('
libname sd1 "d:/sd1";
data sd1.testwps(compress=no);
  xTHOMASx="FINDTHIS";
  ySUZANEy=2**53-1;
  put ySUZANEy hex16.;
run;quit;
');

proc contents data=sd1.testwps;
run;quit;

/*
Data Set Name        SD1.TESTWPS                   Observations          1
Member Type          DATA                          Variables             2
Engine               V9                            Indexes               0
Created              10/24/2016 18:57:15           Observation Length    16
Last Modified        10/24/2016 18:57:15           Deleted Observations  0
Protection                                         Compressed            NO
Data Set Type                                      Sorted                NO
Label
Data Representation  WINDOWS_64
Encoding             wlatin1  Western (Windows)

```
     Engine/Host Dependent Information
```

Data Set Page Size          4096
Number of Data Set Pages    1
First Data Page             1
Max Obs per Page            252
Obs in First Data Page      1
Number of Data Set Repairs  0
Filename                    d:\sd1\testwps.sas7bdat
Release Created             9.0101M3
Host Created                XP_PRO
*/

data _null_;
 infile "d:/sd1/testwps.sas7bdat" lrecl=80 recfm=f;
 input;
 if _infile_ ne repeat('00'x,79) then list;
run;quit;

RULE:     ----+----1----+----2----+----3----+----4----+----5----+----6----+----7----+----8-

1   CHAR  ............Âê.`³..Ï½’...Ç1Œ...."".33..2................"".33..2.3.#3.>.........
    ZONE  000000000000CE86B11CB9000C381111220330030000000000001111220330030302303001000000
    NUMR  0000000000002A10341FD280971C8F01220331224000000000318F0122033122431330E000310000

2   CHAR  ....SAS FILETESTWPS                                                         DATA
    ZONE  00005452444454555552222222222222222222222222222222222222222222222222222222224454
    NUMR  0000313069C545347030000000000000000000000000000000000000000000000000000000004141

3   CHAR      ....?5ÎB”·ÚA?5ÎB”·ÚA..... ÌÀ..... ÌÀ....................9.0101M3XP_PRO......
    ZONE  2222000033C49BD433C49BD4000002CC000002CC0000010000000000000032333343555554000000
    NUMR  00000000F5E247A1F5E247A1000000C0000000C0040000001000100000009E0101D380F02F000000

4   CHAR  ....................................................?5ÎBs{¡'s{¡'s{¡'............
    ZONE  000000000000000000000000000000000000000000000000000033C477A277A277A2000000000000
    NUMR  0000000000000000000000000000000000000000000000000000F5E23B173B173B17000000000000

5   CHAR  .....‚......?5ÎB”·ÚA............................................................
    ZONE  00009811000033C49BD4000000000000000000000000000000000000000000000000000000000000
    NUMR  0000D2430000F5E247A1000000000000000000000000000000000000000000000000000000000000

13  CHAR  ................................................................œ‚..........=...
    ZONE  00000000000000000000000000000000000000000000000000000000000000009811000000003000
    NUMR  0000000000000000000000000000000000000000000000000000000000000000C24300000000DB00

```
                                             š™™™™™¹? = .1 3FB999999999999A
```

14  CHAR  ........ ...à...................ä...0.......¤...@.......€...$.......T...,.......
    ZONE  000000002000E0000000100000000000E00030000000A00040000000800020000000500020000000
    NUMR  02A090000E00010000004E00C00000004C00010000004C00000001000C00400001004C00C0000100

15  CHAR   ...4.......ì...4.......ì...............ÿÿÿÿÿÿ?CFINDTHIS........................
    ZONE  200030000000E00030000000E000000000000000FFFFFF3444445445000000000000000000000000
    NUMR  0C0040000000CB0040000000CB00000010000000FFFFFFF369E44893000000000000000000000000

51  CHAR  ............................................................................þûÿÿ
    ZONE  0000000000000000000000000000000000000000000000000000000000000000000000000000FFFF
    NUMR  0000000000000000000000000000000000000000000000000000000000000000000000000000EBFF

52  CHAR  ................................................þûÿÿ............................
    ZONE  000000000000000000000000000000000000000000000000FFFF0000000000000000000000000000
    NUMR  000000000000000000000000000000000000000000000000EBFF0000000000000000000000000000

53  CHAR  ....................üÿÿÿ .......................................ÿÿÿÿ..........$.
    ZONE  00000000000000000000FFFF2000000000000000000000000000000000000000FFFF100000000020
    NUMR  00000000000000000000CFFF0000000080008000042000008000041000000000FFFF800000000040

54  CHAR  ......,.............ýÿÿÿ4..........>                DATASTEPxTHOMASxySUZANEy....
    ZONE  00000020000000000000FFFF30000000000322222222222222224454554575444457755544470000
    NUMR  800000C0800000000000DFFF40000000000E000000000000000041413450848FD138935A1E590000

55  CHAR  .....üÿÿ4...........................................................üÿÿÿ........
    ZONE  00000FFF300000000000000000000000000000000000000000000000000000000000FFFF00000000
    NUMR  00000CFF4000300070000000000000000000000000000000000000000000C7000000CFFF10006000

56  CHAR  ........ýÿÿÿ................ÿÿÿÿ................þÿÿÿ................ûÿÿÿ........
    ZONE  00000000FFFF0000000000000000FFFF0000000000000000FFFF0000000000000000FFFF00000000
    NUMR  10006000DFFF1000400010004000FFFF1000500010005000EFFF0000000000000000BFFF00000000

57  CHAR  ........úÿÿÿ................ùÿÿÿ................................................
    ZONE  00000000FFFF0000000000000000FFFF000000000000000000000000000000000000000000000000
    NUMR  00000000AFFF00000000000000009FFF000000000000000000000000000000000000000000000000

58  CHAR  ....................................................................öööö........
    ZONE  00000000000000000000000000000000000000000000000000000000000000000000FFFF00000000
    NUMR  00000000000000000000000000000000000000000000000000000000000000000000666620000000

59  CHAR  ÷÷÷÷ð............0".........................................´...ÿÿÿÿÿÿÿÿ........
    ZONE  FFFFF0000000000013201000000000000000000000000000100001000000B000FFFFFFFF00000000
    NUMR  77770000B0000000102000001000000000002000000000000000000000004000FFFFFFFF00000000

61  CHAR  ............................................................œ‚..................
    ZONE  00000000000000000000000000000000000000000000000000000000000098110000000000000000
    NUMR  000000000000000000000000000000000000000000000000000000000000C2430000000000000000

62  CHAR  ................................................................................
    ZONE  00000000000000000000000000000000000000000000000000000000000000000000000000000000
    NUMR  00000000000000000000000010002000100080001000A0001000A000100070000000000000000000

63  CHAR  ................................................................................
    ZONE  00000000000000000000000000000000000000100000000000000000100000000000000000000000
    NUMR  00000000000000000000000000804000000000408000000000C08000C08000000000000000000000

64  CHAR  ......................................½.........................................
    ZONE  00000000000000000000000000000000000000B00000000000000000000000000000000000000000
    NUMR  00000000000000004010108000000000000000D00000000000000000000000000005000000000000

NOTE: 64 records were read from the infile "d:/sd1/testwps.sas7bdat".
NOTE: DATA statement used (Total process time):
      real time           0.06 seconds
      user cpu time       0.01 seconds
      system cpu time     0.04 seconds
      memory              322.09k
      OS Memory           22772.00k
- read the R SAS DATASET

%utl_submit_wps64('
libname sd1 "d:/sd1";
data sd1.check;
  set sd1.testr;
run;quit;
proc contents data=sd1.check;
run;quit;
');

ERROR: Error opening data set "SD1.testr" :
       I/O error: file does not have the expected structure
4         run;

**Comment by Jiang-Li** [comment] 2016-10-25 20:40
Thanks. I also mentioned this problem in the previous post. Is there any solution?

**Comment by evanmiller** [comment] 2016-10-26 05:40
Duplicate of #224. The SAS7BDAT exporter is still experimental, but these reports are helpful.

Will exporting in SAS Transport (XPORT) format meet your needs? See related issue https://github.com/WizardMac/ReadStat/issues/29

**Comment by rogerjdeangelis** [comment] 2016-10-26 15:47
Hi Evan

  The V5 xport only supports variable names up to 8 chars and length 200
bytes. Also I have to import on the SAS side.

  I know it is experimental, but do you have sample R code that works? Even
if the output is a special dataset.

**Comment by evanmiller** [comment] 2016-10-27 06:16
I don't have SAS or WPS installed, so I am flying blind here. The SAS writer was designed to provide test coverage for the SAS reader... we decided to expose the functionality in case anyone wanted to try to make it SAS-compatible. Note that sas7bdat is a closed format; the best description so far is Matthew Shotwell's [vignette](https://cran.r-project.org/web/packages/sas7bdat/vignettes/sas7bdat.pdf), which the ReadStat code is largely based off of. But even that vignette is incomplete.

**Comment by rogerjdeangelis** [comment] 2016-11-02 21:31
Hi Evan 

Only commercial products Carolina, WPS and Stat-transfer can create SAS datasets.

There is probably a dozen open applications that can create a SAS V5  xport files but not one open source application. You work is greatly appreciated and difficult.

I created a simple SAS dataset in R and examined it using R along with Mat's documentation and here is what I observed. These are my best guesses as to the outstanding issues.
I decided not to use SAS to analyze SAS datasets.

%utl_submit_r64('
library(haven);
TEST=c(YSUZANEY=33333333);
write_sas(TEST, "d:/haven/testr3.sas7bdat");
');

Here is my analysis (may be faulty)

R creates linux 64bit big endian SAS datasets?

It appears R uses pagesize 4096?
R file size is 9,216, 12,288(on disk) Win 7 64
R filesize should be 4096*2(two pages) = 8192? 
9216=8192=1024 - R has an extra 1024?

I get 4096 for Header Length not 8192.

SAS linux 64bit uses pagetype AMD for meta data  unlike almost all SAS datasets?
R puts meta data after the raw data ie variable name after data. I think this is rare.

For my R dataset data the one observation takes 344 bytes?

What I tried

  1. Filled in dataset name (according to doc)
  2. Padded 64 byte dataset name field with blanks (seems logical)
  3. Corrected time stamps (appear to be 4 bytes should be 8)
  5. Byte 32 is 33 which indicates 64 bit but timestamp is 4 bytes not 8 and in Jan 1995 should be Oct 2016
  6. Byte 39 is 1 which indicates Unix so we have unix 64 bit
  7. A1 should be 4 for since byte 32 is 33x not 33x
  8. A2 =4 because byte 35 is 33x
  9. byte 37 is ok little endian  so unix 64 bit little endian
 11. 164+8 Sluged in 8 byte made up timestamps(time since jan 1960 41DAB87CACFF85BAx) little endian floats
 12. 196+4 Header length  4096 (OK)
 13. 200+4 Initial page size  R 2 bytes changed to 4096?
 14. 204+4 R has zero tried  1
 15. 216+8 Slugged 212-299 bytes using various ascii text  Mats doc
 16. 336+8 slugged 41DAB87CACFF85BAx 27OCT16:13:03:48  R had 0000000000000000x
 17. 338+8 R 4,096

There are offset and record differences after this.

Header does not seem to end at 4096 as it should?
R header ends much later?

Location of variable name YSUZANEY 4,816
Location of 33333333  5,160

Having dificulty determining page type.
SAS linux 64bit uses pagetype AMD

**Comment by evanmiller** [comment] 2016-11-03 05:59
Just a quick tip, ReadStat uses a header of 1024 bytes and a page size of 4096 bytes. So the file you're examining has 2 pages (1024 + 2 * 4096). The first page is of type META and the second is of type DATA. In 64-bit files the type appears at offset 32 within the page. See here for page type constants:

https://github.com/WizardMac/ReadStat/blob/master/src/sas/readstat_sas.h#L87-L91

**Closed** 2017-01-24 15:40 UTC

**Comment by rogerjdeangelis** [comment] 2017-01-24 20:02
I would appreciate you keeping this open until 

Perhaps, you could add a statement to the documentation that 'write_sas' only produces SAS datasets that can be read by R and we are woking on an exportable SAS dataset

'write_sas' does not produce a SAS dataset that can be read by SAS, WPS, Corolina or StatTransfer?

**Comment by hadley** [comment] 2017-01-24 20:05
You've filed a whole bunch of issues, none of which I can easily reproduce.

**Comment by rogerjdeangelis** [comment] 2017-01-24 20:59
​Your efforts are appreciated, this is a difficult problem and I am willing
to help.

I suggest you down load the free version of either StatTransfer or WPS.
StatTransfer is probably a better choice because  has a simple one page gui
to read the SAS dataset R creates​.

run this R code

library(haven);
write_sas(mtcars,"d:/sd1/mtcars.sas7bdat");

open StatTransfer (free edition)

Select SAS dataset and loaction of SAS datase
hit submit
"d:/sd1/mtcars.sas7bdat"

You get this error

1/24/17 15:48:47: If you cannot solve this problem after reviewing the
documentation,
01/24/17 15:48:47: please go to the "Log" tab to send an error report to
Circle Systems
01/24/17 15:48:47: Error reading dictionary - SAS dataset
(D:/sd1/mtcars.sas7bdat)
Processing sas dataset dictionary was stopped because of the error (6).
Please complete our help form at www.stattransfer.com/support/help.html
Please check log on the "Log" tab. since it may contain additional details.

The real problem is not the 1024 header but an unsupported offset.
I think byte 37 should be 33x  not 22x, see my original post. (the correct
numbers are in that issue)

If you fix the offset to be the one used in all Matt Shotwell examples, ie
3 not 2 then I am willing
to test the dataset R creates.

I think I was able to repair one of the R datasets and get to alittle less
serious error, 'premature end of page'
