### ISSUE TITLE
Read_SAS failing with large SAS file

### ISSUE THREAD

**Issue by jeremy17-Endo** [tidyverse/haven#479] opened 2019-10-25 14:21 UTC
I’m having issues when reading in SAS (.sas7bdat) files that are close to 4GB.  I get the error that the R session was abnormally terminated due to an unexpected crash.
I have multiple 2.5GB files that are reading in less than 5 minutes, which seems right.  I’m using the read_sas function in the HAVEN package.  Is this an issue with HAVEN handling large files or is it a not sufficient memory issue in the LINUX environment?

**Comment by evanmiller** [comment] 2019-10-27 12:50
Do you have a link to the file that is failing?

**Comment by hadley** [comment] 2019-11-06 20:02
I'm closing this issue since it's been 10 days. @jeremy17-Endo if you can provide a reproducible example, we can reopen the issue.

**Closed by hadley** 2019-11-06 20:02 UTC
