### ISSUE TITLE
Problem with importing SAS dataset in R studio

### ISSUE THREAD

**Issue by prashantj** [tidyverse/haven#241] opened 2016-11-25 04:56 UTC
Dear Sir,

When I try to import SAS data set using haven package, i have got the following message and it could not import. I am attaching the scrren shot of the message.
![sas import issue](https://cloud.githubusercontent.com/assets/2465597/20614851/2dd92062-b2f9-11e6-9c97-7984c3127575.jpg)
The message is:
****Is this valid spss or sas or stata file? file must be a string , raw vector or a connection****
Please help. 
![sas import issue](https://cloud.githubusercontent.com/assets/2465597/20614863/75877120-b2f9-11e6-958c-0d35251edf53.jpg)
please help,
Looking forward for your reply,
regards,
Prashant

**Comment by hadley** [comment] 2017-01-25 14:28
Please provide a reproducible example. There are three things you need to include to make your example reproducible: required packages, data, and code.

1.  **Packages** should be loaded at the top of the script, so it's easy to
    see which ones the example needs. This is a good time to check that you're
    using the latest version of each package: it's possible you've discovered
    a bug that been fixed since you installed the package.

1.  The easiest way to include **data** in a question is to use `dput()` to 
    generate the R code to recreate it. For example, to recreate the `mtcars` 
    dataset in R, I'd perform the following steps:
  
    1. Run `dput(mtcars)` in R
    2. Copy the output
    3. In my reproducible script, type `mtcars <- ` then paste.
    
    Try and find the smallest subset of your data that still reveals
    the problem.

1.  Spend a little bit of time ensuring that your **code** is easy for others to
    read:

    * Make sure you've used spaces and your variable names are concise, yet
      informative.
    
    * Use comments to indicate where your problem lies.
    
    * Do your best to remove everything that is not related to the problem.  
      The shorter your code is, the easier it is to understand, and the 
      easier it is to fix.

Finish by checking that you have actually made a reproducible example by starting a fresh R session and copying and pasting your script in.

**Comment by hadley** [comment] 2017-01-30 14:26
I've closed this issue due to lack of requested reprex. If you still care about this bug, please open a new issue with a reprex.

**Closed by hadley** 2017-01-30 14:26 UTC
Labels: reprex
